/** HotelStory channel, rate-block, and operational catalog domain service. */
import type { PmsDatabase, PmsPreparedStatement } from "../../../db/pms-database";

export class HotelStoryCatalogError extends Error {
  constructor(message:string,public status=400){super(message);}
}

type Row=Record<string,unknown>;
const isoDate=/^\d{4}-\d{2}-\d{2}$/u;
const codePattern=/^[A-Z0-9_]{2,40}$/u;
const asText=(value:unknown,max=500)=>String(value??"").trim().slice(0,max);
const asInt=(value:unknown,label:string,min:number,max:number)=>{const number=Number(value);if(!Number.isInteger(number)||number<min||number>max)throw new HotelStoryCatalogError(`${label} 범위를 확인하세요.`);return number;};
const asMoney=(value:unknown,label:string)=>{const number=Number(value);if(!Number.isFinite(number)||number<0||number>999_999_999_999)throw new HotelStoryCatalogError(`${label}을 확인하세요.`);return number;};
const jsonArray=(value:unknown)=>{try{const parsed=JSON.parse(String(value??"[]"));if(!Array.isArray(parsed)||parsed.some(item=>typeof item!=="string"))throw new Error();return parsed as string[];}catch{throw new HotelStoryCatalogError("선택 목록 형식을 확인하세요.");}};
const jsonWeekdays=(value:unknown)=>{try{const parsed=JSON.parse(String(value??"[]"));if(!Array.isArray(parsed))throw new Error();const result=parsed.map(Number);if(result.some(item=>!Number.isInteger(item)||item<0||item>6)||new Set(result).size!==result.length)throw new Error();return result;}catch{throw new HotelStoryCatalogError("적용 요일을 확인하세요.");}};
const jsonObject=(value:unknown)=>{try{const parsed=JSON.parse(String(value??"{}"));if(!parsed||Array.isArray(parsed)||typeof parsed!=="object")throw new Error();return parsed as Record<string,unknown>;}catch{throw new HotelStoryCatalogError("공급사 설정 형식을 확인하세요.");}};
const dates=(from:string,to:string)=>{if(!isoDate.test(from)||!isoDate.test(to)||to<from)throw new HotelStoryCatalogError("조회 기간을 확인하세요.");const result:string[]=[];for(let cursor=new Date(`${from}T00:00:00Z`),end=new Date(`${to}T00:00:00Z`);cursor<=end;cursor.setUTCDate(cursor.getUTCDate()+1))result.push(cursor.toISOString().slice(0,10));if(result.length>31)throw new HotelStoryCatalogError("블럭요금 매트릭스는 한 번에 최대 31일까지 조회할 수 있습니다.");return result;};
const addDays=(date:string,amount:number)=>{const value=new Date(`${date}T00:00:00Z`);value.setUTCDate(value.getUTCDate()+amount);return value.toISOString().slice(0,10);};
const cutoffReached=(mapping:Row,stayDate:string)=>{const cutoffDate=addDays(String(mapping.business_date),Number(mapping.cutoff_days||0));return stayDate<cutoffDate||(stayDate===cutoffDate&&String(mapping.local_time||"00:00")>=String(mapping.cutoff_time||"23:59").slice(0,5));};
const chunks=<T>(values:T[],size=350)=>Array.from({length:Math.ceil(values.length/size)},(_,index)=>values.slice(index*size,(index+1)*size));

function audit(db:PmsDatabase,propertyId:string,actor:string,action:string,entityType:string,entityId:string,before:unknown,after:unknown,now:string){
  return db.prepare("INSERT INTO audit_logs(id,property_id,actor,action,entity_type,entity_id,before_json,after_json,created_at) VALUES (?,?,?,?,?,?,?::jsonb,?::jsonb,?)").bind(crypto.randomUUID(),propertyId,actor,action,entityType,entityId,before,after,now);
}
function receipt(db:PmsDatabase,propertyId:string,key:string|undefined,action:string,actor:string,now:string){return key?db.prepare("INSERT INTO idempotency_keys VALUES (?,?,?,?,?)").bind(key,propertyId,action,actor,now):null;}

/** Two-list channel settings use a small catalog projection instead of full PMS state. */
export async function loadChannelCatalog(db:PmsDatabase){
  const [catalog,cutoffs,plans,connections]=await db.batch([
    db.prepare(`SELECT cc.*,pcs.id setting_id,pcs.connection_id,pcs.active setting_active,pcs.sort_order setting_sort_order,
      pcs.supplier_name,pcs.supplier_code,pcs.supplier_config,pcs.external_property_id,pcs.separate_management,
      pcs.sales_cutoff_days,pcs.version setting_version,c.status connection_status,c.environment,c.last_sync_at
      FROM channel_catalog cc LEFT JOIN property_channel_settings pcs ON pcs.catalog_id=cc.id AND pcs.property_id=cc.property_id
      LEFT JOIN channel_connections c ON c.id=pcs.connection_id AND c.property_id=pcs.property_id
      WHERE cc.property_id=pms_current_property_id() AND cc.active
      ORDER BY CASE WHEN pcs.id IS NULL THEN 1 ELSE 0 END,COALESCE(pcs.sort_order,cc.sort_order),cc.display_name`),
    db.prepare(`SELECT cpc.*,cc.display_name channel_name,rp.code rate_plan_code,rp.name rate_plan_name
      FROM channel_product_cutoffs cpc JOIN property_channel_settings pcs ON pcs.id=cpc.setting_id AND pcs.property_id=cpc.property_id
      JOIN channel_catalog cc ON cc.id=pcs.catalog_id AND cc.property_id=pcs.property_id
      JOIN rate_plans rp ON rp.id=cpc.rate_plan_id AND rp.property_id=cpc.property_id
      WHERE cpc.property_id=pms_current_property_id() ORDER BY cc.display_name,rp.sort_order,rp.code`),
    db.prepare("SELECT id,code,name,active,sort_order FROM rate_plans WHERE property_id=pms_current_property_id() ORDER BY active DESC,sort_order,code"),
    db.prepare("SELECT id,provider,external_property_id,name,environment,status,last_sync_at FROM channel_connections WHERE property_id=pms_current_property_id() ORDER BY provider,name"),
  ]);
  return {catalog:catalog.results,cutoffs:cutoffs.results,ratePlans:plans.results,connections:connections.results};
}

/** Bounded product × channel × room × date projection for the rate-block grid. */
export async function loadRateBlockMatrix(db:PmsDatabase,params:URLSearchParams){
  const from=params.get("from")||"",to=params.get("to")||"",dateList=dates(from,to),requestedConnection=asText(params.get("connectionId"),80),roomTypeId=asText(params.get("roomTypeId"),80);
  const [connectionResult,mappingResult,overrideResult,poolResult]=await db.batch([
    db.prepare(`SELECT c.id,c.provider,c.name,cc.display_name,cc.integration_mode,pcs.sort_order,pcs.sales_cutoff_days
      FROM property_channel_settings pcs JOIN channel_catalog cc ON cc.id=pcs.catalog_id AND cc.property_id=pcs.property_id
      JOIN channel_connections c ON c.id=pcs.connection_id AND c.property_id=pcs.property_id
      WHERE pcs.property_id=pms_current_property_id() AND pcs.active AND c.status='ACTIVE'
      ORDER BY pcs.sort_order,cc.display_name`),
    db.prepare(`SELECT m.id,m.connection_id,m.room_type_id,m.rate_plan,m.external_room_type_id,m.external_rate_plan_id,
      c.provider,c.name connection_name,rt.code room_type_code,rt.name room_type_name,rp.id rate_plan_id,rp.name rate_plan_name,
      rprt.base_rate,COALESCE(cpc.cutoff_days,pcs.sales_cutoff_days,0) cutoff_days,COALESCE(cpc.cutoff_time,'23:59'::time) cutoff_time,
      p.business_date,to_char(clock_timestamp() AT TIME ZONE p.timezone,'HH24:MI') local_time,
      contract.contract_type,contract.commission_percent
      FROM channel_mappings m JOIN channel_connections c ON c.id=m.connection_id AND c.property_id=m.property_id
      JOIN property_channel_settings pcs ON pcs.connection_id=c.id AND pcs.property_id=c.property_id AND pcs.active
      JOIN room_types rt ON rt.id=m.room_type_id AND rt.property_id=m.property_id AND rt.active
      JOIN rate_plans rp ON rp.property_id=m.property_id AND rp.code=m.rate_plan AND rp.active
      JOIN properties p ON p.id=m.property_id
      JOIN rate_plan_room_types rprt ON rprt.property_id=m.property_id AND rprt.rate_plan_id=rp.id AND rprt.room_type_id=rt.id AND rprt.active
      LEFT JOIN channel_product_cutoffs cpc ON cpc.property_id=m.property_id AND cpc.setting_id=pcs.id AND cpc.rate_plan_id=rp.id AND cpc.active
      LEFT JOIN channel_contracts contract ON contract.connection_id=c.id AND contract.property_id=c.property_id AND contract.status='ACTIVE'
      WHERE m.property_id=pms_current_property_id() AND m.active AND c.status='ACTIVE'
        AND (?='' OR m.connection_id=?) AND (?='' OR m.room_type_id=?)
      ORDER BY pcs.sort_order,rt.code,rp.sort_order,rp.code`).bind(requestedConnection,requestedConnection,roomTypeId,roomTypeId),
    db.prepare("SELECT * FROM channel_rate_overrides WHERE property_id=pms_current_property_id() AND stay_date BETWEEN ? AND ? AND (?='' OR connection_id=?) AND (?='' OR room_type_id=?)").bind(from,to,requestedConnection,requestedConnection,roomTypeId,roomTypeId),
    db.prepare(`WITH physical AS (
        SELECT room_type_id,COUNT(*)::int count FROM rooms WHERE property_id=pms_current_property_id() AND active AND housekeeping_status<>'OUT_OF_SERVICE' GROUP BY room_type_id
      ), booked AS (
        SELECT room_type_id,stay_date,COUNT(*)::int count FROM reservation_type_nights WHERE property_id=pms_current_property_id() AND stay_date BETWEEN ? AND ? GROUP BY room_type_id,stay_date
      ), held AS (
        SELECT bi.room_type_id,bi.stay_date,SUM(GREATEST(0,bi.current_rooms-bi.picked_up))::int count FROM block_inventory bi JOIN business_blocks bb ON bb.id=bi.block_id AND bb.property_id=bi.property_id
        WHERE bi.property_id=pms_current_property_id() AND bi.stay_date BETWEEN ? AND ? AND bb.status IN ('TENTATIVE','DEFINITE') AND bb.deduct_inventory GROUP BY bi.room_type_id,bi.stay_date
      ) SELECT rt.id room_type_id,d.stay_date::date stay_date,COALESCE(p.count,0) physical,COALESCE(b.count,0) booked,COALESCE(h.count,0) held
      FROM room_types rt CROSS JOIN generate_series(?::date,?::date,interval '1 day') d(stay_date)
      LEFT JOIN physical p ON p.room_type_id=rt.id LEFT JOIN booked b ON b.room_type_id=rt.id AND b.stay_date=d.stay_date LEFT JOIN held h ON h.room_type_id=rt.id AND h.stay_date=d.stay_date
      WHERE rt.property_id=pms_current_property_id() AND rt.active AND (?='' OR rt.id=?) ORDER BY rt.code,d.stay_date`).bind(from,to,from,to,from,to,roomTypeId,roomTypeId),
  ]);
  const overrides=new Map(overrideResult.results.map(row=>[`${row.mapping_id}:${row.stay_date}`,row])),pool=new Map(poolResult.results.map(row=>[`${row.room_type_id}:${String(row.stay_date)}`,row]));
  const rows=mappingResult.results.map(mapping=>({
    ...mapping,
    cells:dateList.map(stayDate=>{const override=overrides.get(`${mapping.id}:${stayDate}`),capacity=pool.get(`${mapping.room_type_id}:${stayDate}`),physical=Number(capacity?.physical||0),booked=Number(capacity?.booked||0),held=Number(capacity?.held||0),poolAvailable=Math.max(0,physical-booked-held);return {stayDate,physical,booked,held,poolAvailable,allocation:override?.allocation==null?physical:Number(override.allocation),sellRate:Number(override?.sell_rate??mapping.base_rate),netRate:override?.net_rate==null?null:Number(override.net_rate),closed:Boolean(override?.closed)||cutoffReached(mapping,stayDate),minStay:Number(override?.min_stay||1),cta:Boolean(override?.close_to_arrival),ctd:Boolean(override?.close_to_departure),version:Number(override?.version||0)};}),
  }));
  return {range:{from,to,days:dateList.length},dates:dateList,connections:connectionResult.results,selectedConnectionId:requestedConnection||String(connectionResult.results[0]?.id||""),rows};
}

export async function loadOperationalCatalogs(db:PmsDatabase){
  const [seasons,holidays,amenities,services,media]=await db.batch([
    db.prepare("SELECT * FROM property_seasons WHERE property_id=pms_current_property_id() ORDER BY active DESC,start_date,name"),
    db.prepare("SELECT * FROM property_holidays WHERE property_id=pms_current_property_id() ORDER BY stay_date,name"),
    db.prepare("SELECT * FROM amenity_catalog WHERE property_id=pms_current_property_id() ORDER BY active DESC,sort_order,name"),
    db.prepare("SELECT * FROM service_catalog WHERE property_id=pms_current_property_id() ORDER BY active DESC,sort_order,name"),
    db.prepare("SELECT id,scope,room_type_id,role,public_url,alt_text,sort_order,active,created_at FROM website_media WHERE property_id=pms_current_property_id() ORDER BY active DESC,sort_order,created_at DESC"),
  ]);
  return {seasons:seasons.results,holidays:holidays.results,amenities:amenities.results,services:services.results,media:media.results};
}

async function currentRow(db:PmsDatabase,table:string,id:string){return db.prepare(`SELECT * FROM ${table} WHERE id=? AND property_id=pms_current_property_id()`).bind(id).first<Row>();}

/** Handles catalog commands and returns false for actions owned by another domain module. */
export async function handleHotelStoryCatalogAction(db:PmsDatabase,body:Record<string,string>,principal:{propertyId:string;email:string},now:string,idempotencyKey?:string){
  const propertyId=principal.propertyId,actor=principal.email,statements:PmsPreparedStatement[]=[];
  if(body.action==="upsert_channel_catalog"){
    const id=body.catalogId||crypto.randomUUID(),before=body.catalogId?await currentRow(db,"channel_catalog",id):null,providerCode=asText(body.providerCode,40).toUpperCase(),displayName=asText(body.displayName,100),channelClass=["OTA","META","DIRECT","WHOLESALE","OTHER"].includes(body.channelClass)?body.channelClass:"OTHER",integrationMode=body.integrationMode==="INTEGRATED"?"INTEGRATED":"MANUAL",description=asText(body.description,500),sortOrder=asInt(body.sortOrder||"100","정렬 순서",0,9999);
    if(!codePattern.test(providerCode)||!displayName)throw new HotelStoryCatalogError("채널 코드와 이름을 확인하세요.");
    if(before){if(Number(body.expectedVersion||before.version)!==Number(before.version||1))throw new HotelStoryCatalogError("다른 사용자가 채널을 먼저 변경했습니다.",409);statements.push(db.prepare("UPDATE channel_catalog SET display_name=?,channel_class=?,integration_mode=?,description=?,sort_order=?,updated_at=?,updated_by=? WHERE id=? AND property_id=?").bind(displayName,channelClass,integrationMode,description,sortOrder,now,actor,id,propertyId));}
    else statements.push(db.prepare("INSERT INTO channel_catalog(id,property_id,provider_code,display_name,channel_class,integration_mode,description,active,sort_order,created_at,updated_at,updated_by) VALUES (?,?,?,?,?,?,?,true,?,?,?,?)").bind(id,propertyId,providerCode,displayName,channelClass,integrationMode,description,sortOrder,now,now,actor));
    statements.push(audit(db,propertyId,actor,before?"UPDATE_CHANNEL_CATALOG":"CREATE_CHANNEL_CATALOG","channel_catalog",id,before,{providerCode,displayName,channelClass,integrationMode,description,sortOrder},now));
  } else if(body.action==="configure_property_channel"){
    const catalog=await currentRow(db,"channel_catalog",body.catalogId);if(!catalog||!catalog.active)throw new HotelStoryCatalogError("설정할 채널을 찾지 못했습니다.",404);
    const existing=await db.prepare("SELECT * FROM property_channel_settings WHERE catalog_id=? AND property_id=pms_current_property_id()").bind(body.catalogId).first<Row>(),active=body.active!=="false",sortOrder=asInt(body.sortOrder||catalog.sort_order,"정렬 순서",0,9999),supplierName=asText(body.supplierName,100),supplierCode=asText(body.supplierCode,100),supplierConfig=jsonObject(body.supplierConfig),externalPropertyId=asText(body.externalPropertyId,120),separateManagement=body.separateManagement==="true",salesCutoffDays=asInt(body.salesCutoffDays||"0","판매 마감일",0,730);let connectionId=asText(body.connectionId,80);
    if(existing&&Number(body.expectedVersion||existing.version)!==Number(existing.version))throw new HotelStoryCatalogError("다른 사용자가 채널 설정을 먼저 변경했습니다.",409);
    if(catalog.integration_mode==="INTEGRATED"&&!connectionId&&catalog.provider_code!=="DIRECT_WEB"){
      if(!externalPropertyId)throw new HotelStoryCatalogError("연동 채널은 외부 호텔 ID가 필요합니다.");connectionId=crypto.randomUUID();statements.push(db.prepare("INSERT INTO channel_connections(id,property_id,provider,external_property_id,name,environment,status,last_sync_at,created_at,updated_at,created_by) VALUES (?,?,?,?,?,'SANDBOX',?,NULL,?,?,?)").bind(connectionId,propertyId,catalog.provider_code,externalPropertyId,`${catalog.display_name} 연결`,active?"ACTIVE":"INACTIVE",now,now,actor));
    } else if(connectionId){const connection=await currentRow(db,"channel_connections",connectionId);if(!connection)throw new HotelStoryCatalogError("연결 정보를 찾지 못했습니다.");statements.push(db.prepare("UPDATE channel_connections SET status=?,external_property_id=CASE WHEN ?='' THEN external_property_id ELSE ? END,updated_at=? WHERE id=? AND property_id=?").bind(active?"ACTIVE":"INACTIVE",externalPropertyId,externalPropertyId,now,connectionId,propertyId));}
    if(existing?.connection_id&&existing.connection_id!==connectionId)statements.push(db.prepare("UPDATE channel_connections SET status='INACTIVE',updated_at=? WHERE id=? AND property_id=?").bind(now,existing.connection_id,propertyId));
    const id=String(existing?.id||crypto.randomUUID()),after={catalogId:body.catalogId,connectionId:connectionId||null,active,sortOrder,supplierName,supplierCode,supplierConfig,externalPropertyId,separateManagement,salesCutoffDays,version:Number(existing?.version||0)+1};
    statements.push(db.prepare("INSERT INTO property_channel_settings(id,property_id,catalog_id,connection_id,active,sort_order,supplier_name,supplier_code,supplier_config,external_property_id,separate_management,sales_cutoff_days,version,created_at,updated_at,updated_by) VALUES (?,?,?,?,?,?,?,?,?::jsonb,?,?,?,?,?,?,?) ON CONFLICT(property_id,catalog_id) DO UPDATE SET connection_id=excluded.connection_id,active=excluded.active,sort_order=excluded.sort_order,supplier_name=excluded.supplier_name,supplier_code=excluded.supplier_code,supplier_config=excluded.supplier_config,external_property_id=excluded.external_property_id,separate_management=excluded.separate_management,sales_cutoff_days=excluded.sales_cutoff_days,version=property_channel_settings.version+1,updated_at=excluded.updated_at,updated_by=excluded.updated_by").bind(id,propertyId,body.catalogId,connectionId||null,active,sortOrder,supplierName,supplierCode,supplierConfig,externalPropertyId,separateManagement,salesCutoffDays,1,now,now,actor));
    statements.push(audit(db,propertyId,actor,existing?"UPDATE_PROPERTY_CHANNEL":"CONFIGURE_PROPERTY_CHANNEL","property_channel_setting",id,existing,after,now));
  } else if(body.action==="set_property_channel_active"){
    const before=await currentRow(db,"property_channel_settings",body.settingId);if(!before)throw new HotelStoryCatalogError("채널 설정을 찾지 못했습니다.",404);if(Number(body.expectedVersion)!==Number(before.version))throw new HotelStoryCatalogError("다른 사용자가 채널 상태를 먼저 변경했습니다.",409);const active=body.active==="true";
    statements.push(db.prepare("UPDATE property_channel_settings SET active=?,version=version+1,updated_at=?,updated_by=? WHERE id=? AND property_id=? AND version=?").bind(active,now,actor,body.settingId,propertyId,before.version));if(before.connection_id)statements.push(db.prepare("UPDATE channel_connections SET status=?,updated_at=? WHERE id=? AND property_id=?").bind(active?"ACTIVE":"INACTIVE",now,before.connection_id,propertyId));statements.push(audit(db,propertyId,actor,"SET_PROPERTY_CHANNEL_ACTIVE","property_channel_setting",body.settingId,before,{...before,active,version:Number(before.version)+1},now));
  } else if(body.action==="reorder_property_channels"){
    const orderIds=jsonArray(body.settingIds),current=(await db.prepare("SELECT id,sort_order FROM property_channel_settings WHERE property_id=pms_current_property_id() ORDER BY sort_order,id").all<Row>()).results;if(orderIds.length!==current.length||new Set(orderIds).size!==orderIds.length||orderIds.some(id=>!current.some(row=>row.id===id)))throw new HotelStoryCatalogError("현재 설정된 모든 채널의 순서를 빠짐없이 제출하세요.");orderIds.forEach((id,index)=>statements.push(db.prepare("UPDATE property_channel_settings SET sort_order=?,version=version+1,updated_at=?,updated_by=? WHERE id=? AND property_id=?").bind((index+1)*10,now,actor,id,propertyId)));statements.push(audit(db,propertyId,actor,"REORDER_PROPERTY_CHANNELS","property_channel_setting","channel-order",current,{settingIds:orderIds},now));
  } else if(body.action==="delete_property_channel"){
    const before=await currentRow(db,"property_channel_settings",body.settingId);if(!before)throw new HotelStoryCatalogError("삭제할 채널 설정을 찾지 못했습니다.",404);if(before.connection_id)statements.push(db.prepare("UPDATE channel_connections SET status='INACTIVE',updated_at=? WHERE id=? AND property_id=?").bind(now,before.connection_id,propertyId));statements.push(db.prepare("DELETE FROM property_channel_settings WHERE id=? AND property_id=?").bind(body.settingId,propertyId),audit(db,propertyId,actor,"DELETE_PROPERTY_CHANNEL","property_channel_setting",body.settingId,before,null,now));
  } else if(body.action==="upsert_channel_product_cutoff"){
    const setting=await currentRow(db,"property_channel_settings",body.settingId),plan=await currentRow(db,"rate_plans",body.ratePlanId);if(!setting||!plan)throw new HotelStoryCatalogError("채널과 판매 상품을 확인하세요.");const existing=await db.prepare("SELECT * FROM channel_product_cutoffs WHERE property_id=pms_current_property_id() AND setting_id=? AND rate_plan_id=?").bind(body.settingId,body.ratePlanId).first<Row>(),id=String(existing?.id||crypto.randomUUID()),cutoffDays=asInt(body.cutoffDays||"0","상품 마감일",0,730),cutoffTime=/^\d{2}:\d{2}$/u.test(body.cutoffTime)?body.cutoffTime:"23:59",active=body.active!=="false";
    statements.push(db.prepare("INSERT INTO channel_product_cutoffs(id,property_id,setting_id,rate_plan_id,cutoff_days,cutoff_time,active,version,updated_at,updated_by) VALUES (?,?,?,?,?,?,?,1,?,?) ON CONFLICT(property_id,setting_id,rate_plan_id) DO UPDATE SET cutoff_days=excluded.cutoff_days,cutoff_time=excluded.cutoff_time,active=excluded.active,version=channel_product_cutoffs.version+1,updated_at=excluded.updated_at,updated_by=excluded.updated_by").bind(id,propertyId,body.settingId,body.ratePlanId,cutoffDays,cutoffTime,active,now,actor));statements.push(audit(db,propertyId,actor,existing?"UPDATE_CHANNEL_PRODUCT_CUTOFF":"CREATE_CHANNEL_PRODUCT_CUTOFF","channel_product_cutoff",id,existing,{settingId:body.settingId,ratePlanId:body.ratePlanId,cutoffDays,cutoffTime,active},now));
  } else if(body.action==="delete_channel_product_cutoff"){
    const before=await currentRow(db,"channel_product_cutoffs",body.cutoffId);if(!before)throw new HotelStoryCatalogError("상품 마감 설정을 찾지 못했습니다.",404);statements.push(db.prepare("DELETE FROM channel_product_cutoffs WHERE id=? AND property_id=?").bind(body.cutoffId,propertyId),audit(db,propertyId,actor,"DELETE_CHANNEL_PRODUCT_CUTOFF","channel_product_cutoff",body.cutoffId,before,null,now));
  } else if(body.action==="bulk_update_rate_blocks"){
    const from=body.from,to=body.to,dateList=dates(from,to),weekdays=jsonWeekdays(body.weekdays),selectedDates=dateList.filter(date=>weekdays.includes(new Date(`${date}T00:00:00Z`).getUTCDay())),mappingIds=jsonArray(body.mappingIds);if(!mappingIds.length||!selectedDates.length)throw new HotelStoryCatalogError("채널 상품과 적용 요일을 선택하세요.");if(mappingIds.length*selectedDates.length>5000)throw new HotelStoryCatalogError("한 번에 최대 5,000개 상품·채널·일자 셀을 저장할 수 있습니다.",413);
    const placeholders=mappingIds.map(()=>"?").join(","),mappingRows=(await db.prepare(`SELECT m.*,rp.id rate_plan_id,rprt.base_rate,contract.contract_type,contract.commission_percent,COALESCE(cpc.cutoff_days,pcs.sales_cutoff_days,0) cutoff_days,COALESCE(cpc.cutoff_time,'23:59'::time) cutoff_time,p.business_date,to_char(clock_timestamp() AT TIME ZONE p.timezone,'HH24:MI') local_time FROM channel_mappings m JOIN channel_connections c ON c.id=m.connection_id AND c.property_id=m.property_id AND c.status='ACTIVE' JOIN property_channel_settings pcs ON pcs.connection_id=c.id AND pcs.property_id=c.property_id AND pcs.active JOIN rate_plans rp ON rp.property_id=m.property_id AND rp.code=m.rate_plan AND rp.active JOIN rate_plan_room_types rprt ON rprt.property_id=m.property_id AND rprt.rate_plan_id=rp.id AND rprt.room_type_id=m.room_type_id AND rprt.active JOIN properties p ON p.id=m.property_id LEFT JOIN channel_contracts contract ON contract.connection_id=c.id AND contract.property_id=c.property_id AND contract.status='ACTIVE' LEFT JOIN channel_product_cutoffs cpc ON cpc.property_id=m.property_id AND cpc.setting_id=pcs.id AND cpc.rate_plan_id=rp.id AND cpc.active WHERE m.property_id=? AND m.active AND m.id IN (${placeholders})`).bind(propertyId,...mappingIds).all<Row>()).results;if(mappingRows.length!==mappingIds.length)throw new HotelStoryCatalogError("선택한 채널 상품 중 사용할 수 없는 항목이 있습니다.");
    const poolRows=await db.batch([
      db.prepare(`SELECT room_type_id,COUNT(*)::int physical FROM rooms WHERE property_id=? AND active AND housekeeping_status<>'OUT_OF_SERVICE' AND room_type_id IN (${mappingRows.map(()=>"?").join(",")}) GROUP BY room_type_id`).bind(propertyId,...mappingRows.map(row=>row.room_type_id)),
      db.prepare(`SELECT room_type_id,stay_date,COUNT(*)::int booked FROM reservation_type_nights WHERE property_id=? AND stay_date BETWEEN ? AND ? AND room_type_id IN (${mappingRows.map(()=>"?").join(",")}) GROUP BY room_type_id,stay_date`).bind(propertyId,from,to,...mappingRows.map(row=>row.room_type_id)),
      db.prepare(`SELECT bi.room_type_id,bi.stay_date,SUM(GREATEST(0,bi.current_rooms-bi.picked_up))::int held FROM block_inventory bi JOIN business_blocks bb ON bb.id=bi.block_id AND bb.property_id=bi.property_id WHERE bi.property_id=? AND bi.stay_date BETWEEN ? AND ? AND bb.status IN ('TENTATIVE','DEFINITE') AND bb.deduct_inventory AND bi.room_type_id IN (${mappingRows.map(()=>"?").join(",")}) GROUP BY bi.room_type_id,bi.stay_date`).bind(propertyId,from,to,...mappingRows.map(row=>row.room_type_id)),
      db.prepare(`SELECT mapping_id,stay_date,MAX(revision)::int revision FROM ari_updates WHERE property_id=? AND stay_date BETWEEN ? AND ? AND mapping_id IN (${placeholders}) GROUP BY mapping_id,stay_date`).bind(propertyId,from,to,...mappingIds),
    ]);
    const physical=new Map(poolRows[0].results.map(row=>[String(row.room_type_id),Number(row.physical)])),booked=new Map(poolRows[1].results.map(row=>[`${row.room_type_id}:${row.stay_date}`,Number(row.booked)])),held=new Map(poolRows[2].results.map(row=>[`${row.room_type_id}:${row.stay_date}`,Number(row.held)])),revisions=new Map(poolRows[3].results.map(row=>[`${row.mapping_id}:${row.stay_date}`,Number(row.revision)]));
    const allocation=asInt(body.allocation,"채널 할당",0,100000),sellRate=asMoney(body.sellRate,"채널 판매가"),requestedNet=body.netRate===""?null:asMoney(body.netRate,"호텔 입금가"),closed=body.closed==="true",minStay=asInt(body.minStay||"1","최소 숙박",1,365),cta=body.cta==="true",ctd=body.ctd==="true";const overrideRows:unknown[][]=[],ariRows:unknown[][]=[],outboxRows:unknown[][]=[];
    for(const mapping of mappingRows){const roomPhysical=physical.get(String(mapping.room_type_id))||0;if(allocation>roomPhysical)throw new HotelStoryCatalogError(`${mapping.rate_plan} 채널 할당은 실제 객실 ${roomPhysical}실을 초과할 수 없습니다.`,409);const netRate=mapping.contract_type==="NET_RATE"?requestedNet:null;if(mapping.contract_type==="NET_RATE"&&netRate==null)throw new HotelStoryCatalogError("입금가 계약은 호텔 입금가가 필요합니다.");if(netRate!=null&&netRate>sellRate)throw new HotelStoryCatalogError("호텔 입금가는 채널 판매가보다 클 수 없습니다.");for(const stayDate of selectedDates){const effectiveClosed=closed||cutoffReached(mapping,stayDate),pool=Math.max(0,roomPhysical-(booked.get(`${mapping.room_type_id}:${stayDate}`)||0)-(held.get(`${mapping.room_type_id}:${stayDate}`)||0)),available=effectiveClosed?0:Math.min(allocation,pool),payload={roomstosell:available,allocation,closed:effectiveClosed,minimumstay:minStay,closedonarrival:cta,closedondeparture:ctd,rate:sellRate,netRate,currency:"KRW",date:stayDate,ratePlan:mapping.rate_plan};const ariId=crypto.randomUUID();overrideRows.push([crypto.randomUUID(),propertyId,mapping.connection_id,mapping.id,mapping.room_type_id,stayDate,sellRate,netRate,"KRW",mapping.rate_plan_id,allocation,effectiveClosed,minStay,cta,ctd,now,actor]);ariRows.push([ariId,propertyId,mapping.connection_id,mapping.id,stayDate,(revisions.get(`${mapping.id}:${stayDate}`)||0)+1,available,effectiveClosed,minStay,cta,ctd,sellRate,"KRW",payload,now]);outboxRows.push([crypto.randomUUID(),propertyId,"channel.ari_delta","ari_update",ariId,payload,now]);}}
    for(const part of chunks(overrideRows)){statements.push(db.prepare(`INSERT INTO channel_rate_overrides(id,property_id,connection_id,mapping_id,room_type_id,stay_date,sell_rate,net_rate,currency,rate_plan_id,allocation,closed,min_stay,close_to_arrival,close_to_departure,version,updated_at,updated_by) VALUES ${part.map(()=>"(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)").join(",")} ON CONFLICT(mapping_id,stay_date) DO UPDATE SET sell_rate=excluded.sell_rate,net_rate=excluded.net_rate,currency=excluded.currency,rate_plan_id=excluded.rate_plan_id,allocation=excluded.allocation,closed=excluded.closed,min_stay=excluded.min_stay,close_to_arrival=excluded.close_to_arrival,close_to_departure=excluded.close_to_departure,version=channel_rate_overrides.version+1,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(...part.flat()));}
    for(const part of chunks(ariRows)){statements.push(db.prepare(`INSERT INTO ari_updates(id,property_id,connection_id,mapping_id,stay_date,revision,available,closed,min_stay,close_to_arrival,close_to_departure,rate,currency,payload_json,status,attempts,created_at,sent_at,last_error) VALUES ${part.map(()=>"(?,?,?,?,?,?,?,?,?,?,?,?,?,?::jsonb,'PENDING',0,?,NULL,NULL)").join(",")}`).bind(...part.flat()));}
    for(const part of chunks(outboxRows)){statements.push(db.prepare(`INSERT INTO outbox_events(id,property_id,topic,aggregate_type,aggregate_id,payload_json,status,attempts,created_at,published_at) VALUES ${part.map(()=>"(?,?,?,?,?,?::jsonb,'PENDING',0,?,NULL)").join(",")}`).bind(...part.flat()));}
    statements.push(audit(db,propertyId,actor,"BULK_UPDATE_RATE_BLOCKS","channel_rate_block",`${from}:${to}`,null,{from,to,mappingIds,dates:selectedDates.length,cells:overrideRows.length,allocation,sellRate,netRate:requestedNet,closed,minStay,cta,ctd},now));
  } else if(body.action==="upsert_property_season"){
    const id=body.seasonId||crypto.randomUUID(),before=body.seasonId?await currentRow(db,"property_seasons",id):null,name=asText(body.name,100),seasonType=["PEAK","HIGH","SHOULDER","LOW","EVENT"].includes(body.seasonType)?body.seasonType:"PEAK",startDate=body.startDate,endDate=body.endDate,adjustmentType=["NONE","AMOUNT","PERCENT"].includes(body.adjustmentType)?body.adjustmentType:"NONE",adjustment=Number(body.adjustment||0),active=body.active!=="false";if(!name||!isoDate.test(startDate)||!isoDate.test(endDate)||endDate<startDate||!Number.isFinite(adjustment))throw new HotelStoryCatalogError("성수기 이름·기간·조정값을 확인하세요.");statements.push(db.prepare("INSERT INTO property_seasons(id,property_id,name,season_type,start_date,end_date,adjustment_type,adjustment,active,version,updated_at,updated_by) VALUES (?,?,?,?,?,?,?,?,?,1,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,season_type=excluded.season_type,start_date=excluded.start_date,end_date=excluded.end_date,adjustment_type=excluded.adjustment_type,adjustment=excluded.adjustment,active=excluded.active,version=property_seasons.version+1,updated_at=excluded.updated_at,updated_by=excluded.updated_by WHERE property_seasons.property_id=excluded.property_id").bind(id,propertyId,name,seasonType,startDate,endDate,adjustmentType,adjustment,active,now,actor));statements.push(audit(db,propertyId,actor,before?"UPDATE_PROPERTY_SEASON":"CREATE_PROPERTY_SEASON","property_season",id,before,{name,seasonType,startDate,endDate,adjustmentType,adjustment,active},now));
  } else if(body.action==="delete_property_season"||body.action==="delete_property_holiday"||body.action==="delete_amenity_catalog"||body.action==="delete_service_catalog"){
    const config={delete_property_season:["property_seasons","seasonId","property_season"],delete_property_holiday:["property_holidays","holidayId","property_holiday"],delete_amenity_catalog:["amenity_catalog","amenityId","amenity"],delete_service_catalog:["service_catalog","serviceId","service"]}[body.action]!,before=await currentRow(db,config[0],body[config[1]]);if(!before)throw new HotelStoryCatalogError("삭제할 항목을 찾지 못했습니다.",404);statements.push(db.prepare(`DELETE FROM ${config[0]} WHERE id=? AND property_id=?`).bind(before.id,propertyId),audit(db,propertyId,actor,body.action.toUpperCase(),config[2],String(before.id),before,null,now));
  } else if(body.action==="upsert_property_holiday"){
    const id=body.holidayId||crypto.randomUUID(),before=body.holidayId?await currentRow(db,"property_holidays",id):null,name=asText(body.name,100),stayDate=body.stayDate,holidayType=["PUBLIC","HOTEL","EVENT"].includes(body.holidayType)?body.holidayType:"PUBLIC",active=body.active!=="false";if(!name||!isoDate.test(stayDate))throw new HotelStoryCatalogError("휴일 이름과 날짜를 확인하세요.");statements.push(db.prepare("INSERT INTO property_holidays(id,property_id,stay_date,name,holiday_type,active,version,updated_at,updated_by) VALUES (?,?,?,?,?,?,1,?,?) ON CONFLICT(id) DO UPDATE SET stay_date=excluded.stay_date,name=excluded.name,holiday_type=excluded.holiday_type,active=excluded.active,version=property_holidays.version+1,updated_at=excluded.updated_at,updated_by=excluded.updated_by WHERE property_holidays.property_id=excluded.property_id").bind(id,propertyId,stayDate,name,holidayType,active,now,actor));statements.push(audit(db,propertyId,actor,before?"UPDATE_PROPERTY_HOLIDAY":"CREATE_PROPERTY_HOLIDAY","property_holiday",id,before,{stayDate,name,holidayType,active},now));
  } else if(body.action==="upsert_amenity_catalog"){
    const id=body.amenityId||crypto.randomUUID(),before=body.amenityId?await currentRow(db,"amenity_catalog",id):null,code=asText(body.code,40).toUpperCase(),name=asText(body.name,100),category=["ROOM","BATH","FOOD","WELLNESS","ACCESSIBILITY","OTHER"].includes(body.category)?body.category:"OTHER",iconName=asText(body.iconName,60),sortOrder=asInt(body.sortOrder||"100","정렬 순서",0,9999),active=body.active!=="false";if(!codePattern.test(code)||!name)throw new HotelStoryCatalogError("편의시설 코드와 이름을 확인하세요.");statements.push(db.prepare("INSERT INTO amenity_catalog(id,property_id,code,name,category,icon_name,active,sort_order,version,updated_at,updated_by) VALUES (?,?,?,?,?,?,?,?,1,?,?) ON CONFLICT(id) DO UPDATE SET code=excluded.code,name=excluded.name,category=excluded.category,icon_name=excluded.icon_name,active=excluded.active,sort_order=excluded.sort_order,version=amenity_catalog.version+1,updated_at=excluded.updated_at,updated_by=excluded.updated_by WHERE amenity_catalog.property_id=excluded.property_id").bind(id,propertyId,code,name,category,iconName,active,sortOrder,now,actor));statements.push(audit(db,propertyId,actor,before?"UPDATE_AMENITY":"CREATE_AMENITY","amenity",id,before,{code,name,category,iconName,active,sortOrder},now));
  } else if(body.action==="upsert_service_catalog"){
    const id=body.serviceId||crypto.randomUUID(),before=body.serviceId?await currentRow(db,"service_catalog",id):null,code=asText(body.code,40).toUpperCase(),name=asText(body.name,100),category=["MEAL","TRANSPORT","SPA","EVENT","ROOM","OTHER"].includes(body.category)?body.category:"OTHER",pricingType=["INCLUDED","FIXED","PER_PERSON","PER_NIGHT"].includes(body.pricingType)?body.pricingType:"FIXED",price=pricingType==="INCLUDED"?0:asMoney(body.price,"서비스 가격"),currency=asText(body.currency||"KRW",3).toUpperCase(),description=asText(body.description,500),sortOrder=asInt(body.sortOrder||"100","정렬 순서",0,9999),active=body.active!=="false";if(!codePattern.test(code)||!name||!/^[A-Z]{3}$/u.test(currency))throw new HotelStoryCatalogError("서비스 코드·이름·통화를 확인하세요.");statements.push(db.prepare("INSERT INTO service_catalog(id,property_id,code,name,category,pricing_type,price,currency,description,active,sort_order,version,updated_at,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,1,?,?) ON CONFLICT(id) DO UPDATE SET code=excluded.code,name=excluded.name,category=excluded.category,pricing_type=excluded.pricing_type,price=excluded.price,currency=excluded.currency,description=excluded.description,active=excluded.active,sort_order=excluded.sort_order,version=service_catalog.version+1,updated_at=excluded.updated_at,updated_by=excluded.updated_by WHERE service_catalog.property_id=excluded.property_id").bind(id,propertyId,code,name,category,pricingType,price,currency,description,active,sortOrder,now,actor));statements.push(audit(db,propertyId,actor,before?"UPDATE_SERVICE":"CREATE_SERVICE","service",id,before,{code,name,category,pricingType,price,currency,description,active,sortOrder},now));
  } else return false;
  const idem=receipt(db,propertyId,idempotencyKey,body.action,actor,now);if(idem)statements.push(idem);await db.batch(statements);return true;
}
