/** Server-side report catalog, filters, masking and export projections. */
import type { PmsDatabase } from "../../../db/pms-database";

export type ReportPrincipal = { email:string; role:string; capabilities:string[] };

export const reportCatalog = [
  { key:"reservations", label:"예약 상세", group:"예약", description:"예약·투숙·취소·노쇼와 고객, 객실, 채널, 잔액을 조회합니다." },
  { key:"booking_curve", label:"시간대별 예약곡선", group:"예약", description:"예약 생성일별 0–6·6–12·12–18·18–24시 예약 유입과 매출을 집계합니다." },
  { key:"occupancy", label:"점유율 · ADR · RevPAR", group:"매출", description:"일자·객실 타입별 판매 가능 객실, 판매 객실, 객실 매출과 핵심 지표입니다." },
  { key:"financials", label:"정산 · 전표", group:"정산", description:"객실료·부대매출·결제·환불·반대전표를 감사 가능한 원장 형태로 조회합니다." },
  { key:"accounting_journal", label:"회계 분개장 · 손익", group:"회계", description:"계정과목·부서별 차변과 대변, 매출, 비용, 손익과 반대전표를 조회합니다." },
  { key:"channel_settlements", label:"채널 판매가 · 입금가", group:"회계", description:"채널 계약별 판매가, 수수료·유통 비용, 호텔 입금가와 지급 상태를 대사합니다." },
  { key:"channel_deposits", label:"채널 입금관리", group:"회계", description:"채널별 미입금·입금 완료 상태와 입금일·메모·회계 전표를 관리합니다." },
  { key:"ar", label:"매출채권 · 미수금", group:"정산", description:"거래처별 청구서, 만기일, 원금, 수납액과 미수 잔액을 조회합니다." },
  { key:"deferred_settlements", label:"후불 정산관리", group:"정산", description:"후불 거래처별 청구·수납·미수·연체 상태와 최종 수납일을 조회합니다." },
  { key:"yoy", label:"전년 대비 예약현황", group:"매출", description:"입실 월 기준 BOOK·REV 실적을 전년 같은 달과 비교합니다." },
  { key:"housekeeping", label:"객실 · 하우스키핑", group:"객실", description:"객실 타입, 프런트 상태, 청소 상태, 작업자와 작업 현황을 조회합니다." },
  { key:"groups", label:"그룹 · 블록", group:"세일즈", description:"그룹 블록의 일정, 원배정, 현재 배정, 픽업과 잔여 객실박을 조회합니다." },
  { key:"channels", label:"채널 · 인터페이스", group:"연동", description:"OTA 인바운드 처리와 아웃바운드 전달 시도의 성공·실패 이력을 조회합니다." },
  { key:"audit", label:"감사 로그", group:"감사", description:"사용자별 변경 작업과 대상 엔터티의 추적 기록을 조회합니다." },
  { key:"room_inventory", label:"객실 마스터", group:"객실", description:"객실 타입과 실제 객실의 판매·운영 상태를 조회합니다." },
] as const;

type ReportKey = typeof reportCatalog[number]["key"];
type Column = { key:string; label:string; type?:"text"|"number"|"currency"|"percent"|"date"|"datetime" };
type SummaryItem = { label:string; value:number|string; format?:"number"|"currency"|"percent" };
type Params = { report:ReportKey; q:string; from:string; to:string; status:string; source:string; roomTypeId:string; scope:string; page:number; pageSize:number; exportMode:boolean };

export class ReportRequestError extends Error { status:number; constructor(message:string,status=400){ super(message); this.status=status; } }

const moneyKinds = "CASE f.kind WHEN 'CHARGE' THEN f.amount WHEN 'PAYMENT' THEN -f.amount WHEN 'CHARGE_REVERSAL' THEN -f.amount WHEN 'PAYMENT_REVERSAL' THEN f.amount WHEN 'REFUND' THEN f.amount ELSE 0 END";
const validDate=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(new Date(`${value}T00:00:00Z`).valueOf());
const dayDiff=(from:string,to:string)=>Math.floor((new Date(`${to}T00:00:00Z`).valueOf()-new Date(`${from}T00:00:00Z`).valueOf())/86400000);
const round=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
const sqlLike=(columns:string[])=>`(${columns.map(column=>`LOWER(COALESCE(${column},'')) LIKE ?`).join(" OR ")})`;
const searchBinds=(q:string,count:number)=>Array.from({length:count},()=>`%${q.toLowerCase()}%`);

function parseParams(input:URLSearchParams,businessDate:string,overrides?:Partial<Params>):Params {
  // Normalize every report through one filter contract. Interactive pages are
  // capped at 100 rows, exports at 25,000, and date ranges at 367 days so a search
  // cannot become an unbounded operational-database scan.
  const rawReport=input.get("report")||"reservations";
  const report=(reportCatalog.some(item=>item.key===rawReport)?rawReport:"reservations") as ReportKey;
  const from=input.get("from")||businessDate, to=input.get("to")||businessDate;
  if(!validDate(from)||!validDate(to)||from>to) throw new ReportRequestError("조회 시작일과 종료일을 올바르게 입력하세요.");
  if(dayDiff(from,to)>366) throw new ReportRequestError("한 번에 조회할 수 있는 기간은 최대 367일입니다.");
  const exportMode=Boolean(overrides?.exportMode);
  const page=Math.max(1,Number(input.get("page"))||1);
  const pageSize=Math.min(exportMode?25000:100,Math.max(10,Number(input.get("pageSize"))||(exportMode?25000:25)));
  return {...{report,q:(input.get("q")||"").trim().slice(0,120),from,to,status:(input.get("status")||"").trim().slice(0,40),source:(input.get("source")||"").trim().slice(0,80),roomTypeId:(input.get("roomTypeId")||"").trim().slice(0,80),scope:(input.get("scope")||"").trim().slice(0,40),page:exportMode?1:page,pageSize,exportMode},...overrides};
}

async function propertyDate(db:PmsDatabase){const row=await db.prepare("SELECT business_date FROM properties WHERE id=pms_current_property_id()").first<{business_date:string}>();return row?.business_date||new Date().toISOString().slice(0,10);}
async function pageQuery(db:PmsDatabase,sql:string,binds:unknown[],params:Params){return (await db.prepare(`${sql} LIMIT ? OFFSET ?`).bind(...binds,params.pageSize,(params.page-1)*params.pageSize).all<Record<string,unknown>>()).results;}
async function scalarCount(db:PmsDatabase,sql:string,binds:unknown[]){const row=await db.prepare(sql).bind(...binds).first<{count:number}>();return Number(row?.count||0);}

async function reservationsReport(db:PmsDatabase,p:Params,principal:ReportPrincipal){
  // Export permission also controls guest contact visibility. Masking is applied
  // before the response is built so restricted PII never reaches the browser.
  const where=["r.property_id=pms_current_property_id()","r.arrival_date<=?","r.departure_date>?"]; const binds:unknown[]=[p.to,p.from];
  if(p.q){where.push(sqlLike(["r.confirmation_no","g.first_name||' '||g.last_name","g.email","g.phone","rm.number","rt.code","r.notes"]));binds.push(...searchBinds(p.q,7));}
  if(p.status){where.push("r.status=?");binds.push(p.status);} if(p.source){where.push("r.source=?");binds.push(p.source);} if(p.roomTypeId){where.push("r.room_type_id=?");binds.push(p.roomTypeId);}
  const from=`FROM reservations r JOIN properties prop ON prop.id=r.property_id JOIN guests g ON g.id=r.guest_id JOIN room_types rt ON rt.id=r.room_type_id LEFT JOIN rooms rm ON rm.id=r.room_id LEFT JOIN folio_entries f ON f.reservation_id=r.id WHERE ${where.join(" AND ")}`;
  const total=await scalarCount(db,`SELECT COUNT(DISTINCT r.id) count ${from}`,binds);
  const rows=await pageQuery(db,`SELECT r.confirmation_no,g.first_name||' '||g.last_name guest_name,g.email,g.phone,rt.code room_type,rm.number room_number,r.arrival_date,r.departure_date,(r.departure_date-r.arrival_date) nights,r.created_at,GREATEST(r.arrival_date-(r.created_at AT TIME ZONE prop.timezone)::date,0) lead_time_days,CASE WHEN EXTRACT(HOUR FROM r.created_at AT TIME ZONE prop.timezone)<6 THEN '00–06' WHEN EXTRACT(HOUR FROM r.created_at AT TIME ZONE prop.timezone)<12 THEN '06–12' WHEN EXTRACT(HOUR FROM r.created_at AT TIME ZONE prop.timezone)<18 THEN '12–18' ELSE '18–24' END booking_time_band,r.status,r.source,r.rate_plan,r.adults,r.children,r.nightly_rate,ROUND(COALESCE(SUM(${moneyKinds}),0),2) balance ${from} GROUP BY r.id,g.id,rt.id,rm.id,prop.timezone ORDER BY r.arrival_date DESC,r.confirmation_no`,binds,p);
  const sums=await db.prepare(`SELECT COUNT(*) reservations,COALESCE(SUM(nights),0) nights,COALESCE(SUM(booked_revenue),0) booked_revenue,COALESCE(SUM(balance),0) balance,COALESCE(AVG(lead_time),0) avg_lead_time FROM (SELECT r.id,(r.departure_date-r.arrival_date) nights,r.nightly_rate*(r.departure_date-r.arrival_date) booked_revenue,GREATEST(r.arrival_date-(r.created_at AT TIME ZONE prop.timezone)::date,0) lead_time,COALESCE(SUM(${moneyKinds}),0) balance ${from} GROUP BY r.id,prop.timezone) x`).bind(...binds).first<Record<string,unknown>>();
  if(!principal.capabilities.includes("REPORT_EXPORT")) for(const row of rows){row.guest_name=String(row.guest_name).slice(0,1)+"**";row.email="권한 필요";row.phone="권한 필요";}
  const columns:Column[]=[{key:"confirmation_no",label:"예약번호"},{key:"guest_name",label:"고객"},{key:"arrival_date",label:"입실",type:"date"},{key:"departure_date",label:"퇴실",type:"date"},{key:"nights",label:"숙박수",type:"number"},{key:"created_at",label:"예약 시각",type:"datetime"},{key:"lead_time_days",label:"리드타임",type:"number"},{key:"booking_time_band",label:"예약 시간대"},{key:"room_type",label:"객실 타입"},{key:"room_number",label:"객실"},{key:"status",label:"상태"},{key:"source",label:"채널"},{key:"rate_plan",label:"요금제"},{key:"nightly_rate",label:"1박 요금",type:"currency"},{key:"balance",label:"잔액",type:"currency"}];
  if(principal.capabilities.includes("REPORT_EXPORT")) columns.splice(2,0,{key:"email",label:"이메일"},{key:"phone",label:"전화"});
  return {columns,rows,total,summary:[{label:"예약",value:Number(sums?.reservations||0),format:"number"},{label:"평균 리드타임",value:round(Number(sums?.avg_lead_time||0)),format:"number"},{label:"객실박",value:Number(sums?.nights||0),format:"number"},{label:"예약 매출",value:round(Number(sums?.booked_revenue||0)),format:"currency"},{label:"게스트 잔액",value:round(Number(sums?.balance||0)),format:"currency"}] as SummaryItem[]};
}

async function occupancyReport(db:PmsDatabase,p:Params){
  // Occupancy, ADR, and RevPAR share the same room-night denominator; deriving them
  // together avoids discrepancies between dashboard totals and exported rows.
  const typeWhere=p.roomTypeId?"WHERE rt.id=?":"";const typeBinds=p.roomTypeId?[p.roomTypeId]:[];
  const qWhere=p.q?"WHERE LOWER(x.room_type||' '||x.room_type_name) LIKE ?":"";const binds:unknown[]=[p.from,p.to,...typeBinds,...(p.q?[`%${p.q.toLowerCase()}%`]:[])];
  const base=`WITH dates(stay_date) AS (SELECT day::date FROM generate_series(?::date,(?::date-INTERVAL '1 day'),INTERVAL '1 day') day), physical AS (SELECT room_type_id,COUNT(*) rooms FROM rooms WHERE property_id=pms_current_property_id() AND active AND housekeeping_status<>'OUT_OF_SERVICE' GROUP BY room_type_id), sold AS (SELECT room_type_id,stay_date,COUNT(*) rooms FROM reservation_type_nights WHERE property_id=pms_current_property_id() GROUP BY room_type_id,stay_date), revenue AS (SELECT n.room_type_id,n.stay_date,SUM(CASE f.kind WHEN 'CHARGE' THEN f.amount WHEN 'CHARGE_REVERSAL' THEN -f.amount ELSE 0 END) amount FROM reservation_type_nights n JOIN folio_entries f ON f.reservation_id=n.reservation_id AND f.business_date=n.stay_date AND f.code='ROOM' WHERE n.property_id=pms_current_property_id() GROUP BY n.room_type_id,n.stay_date), x AS (SELECT d.stay_date,rt.code room_type,rt.name room_type_name,COALESCE(p.rooms,0) available_rooms,COALESCE(s.rooms,0) sold_rooms,ROUND(CASE WHEN COALESCE(p.rooms,0)=0 THEN 0 ELSE COALESCE(s.rooms,0)*100.0/p.rooms END,2) occupancy,ROUND(COALESCE(r.amount,0),2) room_revenue,ROUND(CASE WHEN COALESCE(s.rooms,0)=0 THEN 0 ELSE COALESCE(r.amount,0)*1.0/s.rooms END,2) adr,ROUND(CASE WHEN COALESCE(p.rooms,0)=0 THEN 0 ELSE COALESCE(r.amount,0)*1.0/p.rooms END,2) revpar FROM dates d CROSS JOIN room_types rt LEFT JOIN physical p ON p.room_type_id=rt.id LEFT JOIN sold s ON s.room_type_id=rt.id AND s.stay_date=d.stay_date LEFT JOIN revenue r ON r.room_type_id=rt.id AND r.stay_date=d.stay_date ${typeWhere})`;
  const rows=(await db.prepare(`${base} SELECT x.*,COUNT(*) OVER() total_count,SUM(available_rooms) OVER() summary_available,SUM(sold_rooms) OVER() summary_sold,SUM(room_revenue) OVER() summary_revenue FROM x ${qWhere} ORDER BY stay_date,room_type LIMIT ? OFFSET ?`).bind(...binds,p.pageSize,(p.page-1)*p.pageSize).all<Record<string,unknown>>()).results;
  const aggregate=rows[0]||{},total=Number(aggregate.total_count||0),available=Number(aggregate.summary_available||0),sold=Number(aggregate.summary_sold||0),revenue=Number(aggregate.summary_revenue||0);for(const row of rows){delete row.total_count;delete row.summary_available;delete row.summary_sold;delete row.summary_revenue;}
  return {columns:[{key:"stay_date",label:"일자",type:"date"},{key:"room_type",label:"객실 타입"},{key:"room_type_name",label:"타입명"},{key:"available_rooms",label:"판매 객실",type:"number"},{key:"sold_rooms",label:"판매 완료",type:"number"},{key:"occupancy",label:"점유율",type:"percent"},{key:"room_revenue",label:"객실 매출",type:"currency"},{key:"adr",label:"ADR",type:"currency"},{key:"revpar",label:"RevPAR",type:"currency"}] as Column[],rows,total,summary:[{label:"가용 객실박",value:available,format:"number"},{label:"판매 객실박",value:sold,format:"number"},{label:"점유율",value:available?round(sold*100/available):0,format:"percent"},{label:"ADR",value:sold?round(revenue/sold):0,format:"currency"},{label:"RevPAR",value:available?round(revenue/available):0,format:"currency"}] as SummaryItem[]};
}

async function financialReport(db:PmsDatabase,p:Params){
  const where=["f.property_id=pms_current_property_id()","f.business_date BETWEEN ? AND ?"];const binds:unknown[]=[p.from,p.to];
  if(p.q){where.push(sqlLike(["f.code","f.description","f.payment_method","f.created_by","r.confirmation_no","g.first_name||' '||g.last_name"]));binds.push(...searchBinds(p.q,6));}if(p.status){where.push("f.kind=?");binds.push(p.status);}if(p.source){where.push("COALESCE(f.payment_method,'')=?");binds.push(p.source);}
  const from=`FROM folio_entries f JOIN reservations r ON r.id=f.reservation_id JOIN guests g ON g.id=r.guest_id LEFT JOIN folio_entry_details d ON d.entry_id=f.id LEFT JOIN folio_windows w ON w.id=d.folio_window_id WHERE ${where.join(" AND ")}`;
  const total=await scalarCount(db,`SELECT COUNT(*) count ${from}`,binds);const rows=await pageQuery(db,`SELECT f.business_date,f.created_at,r.confirmation_no,g.first_name||' '||g.last_name guest_name,w.window_no,f.kind,f.code,f.description,f.amount,f.payment_method,d.net_amount,d.tax_amount,d.service_amount,f.created_by ${from} ORDER BY f.business_date DESC,f.created_at DESC`,binds,p);
  const sums=await db.prepare(`SELECT COALESCE(SUM(CASE WHEN f.kind='CHARGE' THEN f.amount WHEN f.kind='CHARGE_REVERSAL' THEN -f.amount ELSE 0 END),0) charges,COALESCE(SUM(CASE WHEN f.kind='PAYMENT' THEN f.amount WHEN f.kind='PAYMENT_REVERSAL' THEN -f.amount WHEN f.kind='REFUND' THEN -f.amount ELSE 0 END),0) payments,COALESCE(SUM(CASE WHEN f.kind='REFUND' THEN f.amount ELSE 0 END),0) refunds,COALESCE(SUM(${moneyKinds}),0) balance ${from}`).bind(...binds).first<Record<string,unknown>>();
  return {columns:[{key:"business_date",label:"영업일",type:"date"},{key:"created_at",label:"처리 시각",type:"datetime"},{key:"confirmation_no",label:"예약번호"},{key:"guest_name",label:"고객"},{key:"window_no",label:"윈도우",type:"number"},{key:"kind",label:"전표 유형"},{key:"code",label:"거래 코드"},{key:"description",label:"적요"},{key:"amount",label:"금액",type:"currency"},{key:"payment_method",label:"결제 수단"},{key:"net_amount",label:"공급가",type:"currency"},{key:"tax_amount",label:"세금",type:"currency"},{key:"service_amount",label:"봉사료",type:"currency"},{key:"created_by",label:"처리자"}] as Column[],rows,total,summary:[{label:"매출",value:round(Number(sums?.charges||0)),format:"currency"},{label:"순결제",value:round(Number(sums?.payments||0)),format:"currency"},{label:"환불",value:round(Number(sums?.refunds||0)),format:"currency"},{label:"게스트 원장",value:round(Number(sums?.balance||0)),format:"currency"}] as SummaryItem[]};
}

async function arReport(db:PmsDatabase,p:Params){
  const where=["i.property_id=pms_current_property_id()","i.issued_date BETWEEN ? AND ?"];const binds:unknown[]=[p.from,p.to];if(p.q){where.push(sqlLike(["i.invoice_no","a.account_no","a.name","r.confirmation_no"]));binds.push(...searchBinds(p.q,4));}if(p.status){where.push("i.status=?");binds.push(p.status);}
  const from=`FROM ar_invoices i JOIN ar_accounts a ON a.id=i.ar_account_id JOIN reservations r ON r.id=i.reservation_id LEFT JOIN ar_ledger_entries l ON l.invoice_id=i.id WHERE ${where.join(" AND ")}`;
  const total=await scalarCount(db,`SELECT COUNT(DISTINCT i.id) count ${from}`,binds);const rows=await pageQuery(db,`SELECT i.invoice_no,a.account_no,a.name account_name,r.confirmation_no,i.issued_date,i.due_date,i.subtotal,i.tax_amount,i.service_amount,i.total,i.status,ROUND(COALESCE(SUM(l.credit),0),2) paid,ROUND(COALESCE(SUM(l.debit-l.credit),0),2) balance ${from} GROUP BY i.id,a.id,r.id ORDER BY i.due_date,i.invoice_no`,binds,p);
  const sums=await db.prepare(`SELECT COALESCE(SUM(x.total),0) invoiced,COALESCE(SUM(x.paid),0) paid,COALESCE(SUM(x.balance),0) balance FROM (SELECT i.id,i.total,COALESCE(SUM(l.credit),0) paid,COALESCE(SUM(l.debit-l.credit),0) balance ${from} GROUP BY i.id) x`).bind(...binds).first<Record<string,unknown>>();
  return {columns:[{key:"invoice_no",label:"청구서"},{key:"account_no",label:"거래처 번호"},{key:"account_name",label:"거래처"},{key:"confirmation_no",label:"예약번호"},{key:"issued_date",label:"발행일",type:"date"},{key:"due_date",label:"만기일",type:"date"},{key:"subtotal",label:"공급가",type:"currency"},{key:"tax_amount",label:"세금",type:"currency"},{key:"service_amount",label:"봉사료",type:"currency"},{key:"total",label:"청구액",type:"currency"},{key:"paid",label:"수납액",type:"currency"},{key:"balance",label:"미수액",type:"currency"},{key:"status",label:"상태"}] as Column[],rows,total,summary:[{label:"총 청구액",value:round(Number(sums?.invoiced||0)),format:"currency"},{label:"수납액",value:round(Number(sums?.paid||0)),format:"currency"},{label:"미수 잔액",value:round(Number(sums?.balance||0)),format:"currency"}] as SummaryItem[]};
}

async function housekeepingReport(db:PmsDatabase,p:Params){
  const where=["rm.property_id=pms_current_property_id()"];const binds:unknown[]=[];if(p.q){where.push(sqlLike(["rm.number","rt.code","rt.name","h.assignee","h.notes"]));binds.push(...searchBinds(p.q,5));}if(p.status){where.push("rm.housekeeping_status=?");binds.push(p.status);}if(p.roomTypeId){where.push("rm.room_type_id=?");binds.push(p.roomTypeId);}
  const from=`FROM rooms rm JOIN room_types rt ON rt.id=rm.room_type_id LEFT JOIN housekeeping_tasks h ON h.room_id=rm.id AND h.business_date=? WHERE ${where.join(" AND ")}`;binds.unshift(p.to);
  const total=await scalarCount(db,`SELECT COUNT(*) count ${from}`,binds);const rows=await pageQuery(db,`SELECT rm.number,rm.floor,rt.code room_type,rt.name room_type_name,rm.front_desk_status,rm.housekeeping_status,COALESCE(h.status,'UNASSIGNED') task_status,h.priority,h.assignee,h.notes,rm.version ${from} ORDER BY rm.floor,rm.number`,binds,p);
  const counts=await db.prepare(`SELECT COUNT(*) rooms,SUM(CASE WHEN rm.housekeeping_status='DIRTY' THEN 1 ELSE 0 END) dirty,SUM(CASE WHEN rm.housekeeping_status IN ('CLEAN','INSPECTED') THEN 1 ELSE 0 END) ready,SUM(CASE WHEN rm.housekeeping_status='OUT_OF_SERVICE' THEN 1 ELSE 0 END) oos ${from}`).bind(...binds).first<Record<string,unknown>>();
  return {columns:[{key:"number",label:"객실"},{key:"floor",label:"층",type:"number"},{key:"room_type",label:"타입"},{key:"room_type_name",label:"타입명"},{key:"front_desk_status",label:"프런트 상태"},{key:"housekeeping_status",label:"청소 상태"},{key:"task_status",label:"작업 상태"},{key:"priority",label:"우선순위",type:"number"},{key:"assignee",label:"담당자"},{key:"notes",label:"메모"}] as Column[],rows,total,summary:[{label:"전체 객실",value:Number(counts?.rooms||0),format:"number"},{label:"청소 필요",value:Number(counts?.dirty||0),format:"number"},{label:"판매 준비",value:Number(counts?.ready||0),format:"number"},{label:"판매 중지",value:Number(counts?.oos||0),format:"number"}] as SummaryItem[]};
}

async function groupsReport(db:PmsDatabase,p:Params){
  const where=["bb.property_id=pms_current_property_id()","bb.arrival_date<=?","bb.departure_date>?"];const binds:unknown[]=[p.to,p.from];if(p.q){where.push(sqlLike(["bb.code","bb.name","ap.name","gp.name"]));binds.push(...searchBinds(p.q,4));}if(p.status){where.push("bb.status=?");binds.push(p.status);}
  const from=`FROM business_blocks bb LEFT JOIN account_profiles ap ON ap.id=bb.account_profile_id LEFT JOIN account_profiles gp ON gp.id=bb.group_profile_id LEFT JOIN block_inventory bi ON bi.block_id=bb.id WHERE ${where.join(" AND ")}`;
  const total=await scalarCount(db,`SELECT COUNT(DISTINCT bb.id) count ${from}`,binds);const rows=await pageQuery(db,`SELECT bb.code,bb.name,ap.name account_name,gp.name group_name,bb.arrival_date,bb.departure_date,bb.status,bb.reservation_method,bb.cutoff_date,bb.deduct_inventory,COALESCE(SUM(bi.original_rooms),0) original_room_nights,COALESCE(SUM(bi.current_rooms),0) current_room_nights,COALESCE(SUM(bi.picked_up),0) picked_up_room_nights,COALESCE(SUM(bi.current_rooms-bi.picked_up),0) remaining_room_nights ${from} GROUP BY bb.id,ap.id,gp.id ORDER BY bb.arrival_date,bb.code`,binds,p);
  const sums=await db.prepare(`SELECT COALESCE(SUM(x.current_rooms),0) allocated,COALESCE(SUM(x.picked_up),0) picked,COALESCE(SUM(x.current_rooms-x.picked_up),0) remaining FROM (SELECT bb.id,COALESCE(SUM(bi.current_rooms),0) current_rooms,COALESCE(SUM(bi.picked_up),0) picked_up ${from} GROUP BY bb.id) x`).bind(...binds).first<Record<string,unknown>>();
  return {columns:[{key:"code",label:"블록 코드"},{key:"name",label:"블록명"},{key:"account_name",label:"회사"},{key:"group_name",label:"그룹"},{key:"arrival_date",label:"입실",type:"date"},{key:"departure_date",label:"퇴실",type:"date"},{key:"status",label:"상태"},{key:"reservation_method",label:"예약 방식"},{key:"cutoff_date",label:"컷오프",type:"date"},{key:"original_room_nights",label:"원배정 객실박",type:"number"},{key:"current_room_nights",label:"현재 객실박",type:"number"},{key:"picked_up_room_nights",label:"픽업 객실박",type:"number"},{key:"remaining_room_nights",label:"잔여 객실박",type:"number"}] as Column[],rows,total,summary:[{label:"블록",value:total,format:"number"},{label:"할당 객실박",value:Number(sums?.allocated||0),format:"number"},{label:"픽업 객실박",value:Number(sums?.picked||0),format:"number"},{label:"잔여 객실박",value:Number(sums?.remaining||0),format:"number"}] as SummaryItem[]};
}

async function channelsReport(db:PmsDatabase,p:Params){
  const where=["a.property_id=pms_current_property_id()","a.created_at::date BETWEEN ?::date AND ?::date"];const binds:unknown[]=[p.from,p.to];if(p.q){where.push(sqlLike(["a.provider","a.aggregate_type","a.aggregate_id","a.error_code","a.error_message"]));binds.push(...searchBinds(p.q,5));}if(p.status){where.push("a.status=?");binds.push(p.status);}if(p.source){where.push("a.provider=?");binds.push(p.source);}
  const from=`FROM integration_delivery_attempts a WHERE ${where.join(" AND ")}`;const total=await scalarCount(db,`SELECT COUNT(*) count ${from}`,binds);const rows=await pageQuery(db,`SELECT a.created_at,a.direction,a.provider,a.aggregate_type,a.aggregate_id,a.attempt_no,a.status,a.http_status,a.error_code,a.error_message,a.created_by ${from} ORDER BY a.created_at DESC`,binds,p);
  const counts=await db.prepare(`SELECT COUNT(*) attempts,SUM(CASE WHEN a.status='ACKED' THEN 1 ELSE 0 END) success,SUM(CASE WHEN a.status='FAILED' THEN 1 ELSE 0 END) failed ${from}`).bind(...binds).first<Record<string,unknown>>();const attempts=Number(counts?.attempts||0),success=Number(counts?.success||0);
  return {columns:[{key:"created_at",label:"처리 시각",type:"datetime"},{key:"direction",label:"방향"},{key:"provider",label:"채널"},{key:"aggregate_type",label:"대상 유형"},{key:"aggregate_id",label:"대상 ID"},{key:"attempt_no",label:"시도",type:"number"},{key:"status",label:"상태"},{key:"http_status",label:"HTTP",type:"number"},{key:"error_code",label:"오류 코드"},{key:"error_message",label:"오류 내용"},{key:"created_by",label:"처리자"}] as Column[],rows,total,summary:[{label:"전송 시도",value:attempts,format:"number"},{label:"성공",value:success,format:"number"},{label:"실패",value:Number(counts?.failed||0),format:"number"},{label:"성공률",value:attempts?round(success*100/attempts):100,format:"percent"}] as SummaryItem[]};
}

async function auditReport(db:PmsDatabase,p:Params){
  const where=["property_id=pms_current_property_id()","created_at::date BETWEEN ?::date AND ?::date"];const binds:unknown[]=[p.from,p.to];if(p.q){where.push(sqlLike(["actor","action","entity_type","entity_id"]));binds.push(...searchBinds(p.q,4));}if(p.status){where.push("action=?");binds.push(p.status);}if(p.source){where.push("actor=?");binds.push(p.source);}
  const from=`FROM audit_logs WHERE ${where.join(" AND ")}`;const total=await scalarCount(db,`SELECT COUNT(*) count ${from}`,binds);const rows=await pageQuery(db,`SELECT created_at,actor,action,entity_type,entity_id,before_json,after_json ${from} ORDER BY created_at DESC`,binds,p);const actors=await scalarCount(db,`SELECT COUNT(DISTINCT actor) count ${from}`,binds);
  return {columns:[{key:"created_at",label:"처리 시각",type:"datetime"},{key:"actor",label:"사용자"},{key:"action",label:"작업"},{key:"entity_type",label:"대상 유형"},{key:"entity_id",label:"대상 ID"},{key:"before_json",label:"변경 전"},{key:"after_json",label:"변경 후"}] as Column[],rows,total,summary:[{label:"감사 이벤트",value:total,format:"number"},{label:"작업 사용자",value:actors,format:"number"}] as SummaryItem[]};
}

async function roomInventoryReport(db:PmsDatabase,p:Params){
  const where=["rm.property_id=pms_current_property_id()"];const binds:unknown[]=[];if(p.q){where.push(sqlLike(["rm.number","rt.code","rt.name","rm.features"]));binds.push(...searchBinds(p.q,4));}if(p.status){where.push("rm.housekeeping_status=?");binds.push(p.status);}if(p.roomTypeId){where.push("rm.room_type_id=?");binds.push(p.roomTypeId);}
  const from=`FROM rooms rm JOIN room_types rt ON rt.id=rm.room_type_id WHERE ${where.join(" AND ")}`;const total=await scalarCount(db,`SELECT COUNT(*) count ${from}`,binds);const rows=await pageQuery(db,`SELECT rt.code room_type,rt.name room_type_name,rt.base_rate,rt.capacity,rm.number,rm.floor,rm.front_desk_status,rm.housekeeping_status,rm.features,rm.version ${from} ORDER BY rm.floor,rm.number`,binds,p);const types=await scalarCount(db,`SELECT COUNT(DISTINCT rt.id) count ${from}`,binds);
  return {columns:[{key:"room_type",label:"타입"},{key:"room_type_name",label:"타입명"},{key:"base_rate",label:"기준 요금",type:"currency"},{key:"capacity",label:"기준 인원",type:"number"},{key:"number",label:"객실"},{key:"floor",label:"층",type:"number"},{key:"front_desk_status",label:"프런트 상태"},{key:"housekeeping_status",label:"청소 상태"},{key:"features",label:"특성"},{key:"version",label:"버전",type:"number"}] as Column[],rows,total,summary:[{label:"객실 타입",value:types,format:"number"},{label:"객실",value:total,format:"number"}] as SummaryItem[]};
}

async function accountingJournalReport(db:PmsDatabase,p:Params){
  const where=["e.property_id=pms_current_property_id()","e.business_date BETWEEN ? AND ?"],binds:unknown[]=[p.from,p.to];
  if(p.q){where.push(sqlLike(["e.entry_no","e.description","e.vendor","e.created_by","a.code","a.name","l.department","l.memo"]));binds.push(...searchBinds(p.q,8));}
  if(p.status){where.push("e.entry_type=?");binds.push(p.status);}if(p.source){where.push("e.source_type=?");binds.push(p.source);}
  const from=`FROM accounting_journal_entries e JOIN accounting_journal_lines l ON l.journal_entry_id=e.id JOIN accounting_accounts a ON a.id=l.account_id WHERE ${where.join(" AND ")}`;
  const total=await scalarCount(db,`SELECT COUNT(*) count ${from}`,binds),rows=await pageQuery(db,`SELECT e.business_date,e.entry_no,e.entry_type,e.source_type,e.description,e.vendor,e.status,a.code account_code,a.name account_name,a.account_type,l.department,l.debit,l.credit,l.memo,e.created_by ${from} ORDER BY e.business_date DESC,e.created_at DESC,e.entry_no,a.code`,binds,p);
  const sums=await db.prepare(`SELECT COALESCE(SUM(l.debit),0) debit,COALESCE(SUM(l.credit),0) credit,COALESCE(SUM(CASE WHEN a.account_type='REVENUE' THEN l.credit-l.debit ELSE 0 END),0) revenue,COALESCE(SUM(CASE WHEN a.account_type='EXPENSE' THEN l.debit-l.credit ELSE 0 END),0) expense ${from}`).bind(...binds).first<Record<string,unknown>>(),revenue=Number(sums?.revenue||0),expense=Number(sums?.expense||0);
  return {columns:[{key:"business_date",label:"영업일",type:"date"},{key:"entry_no",label:"전표번호"},{key:"entry_type",label:"전표 유형"},{key:"source_type",label:"출처"},{key:"description",label:"적요"},{key:"vendor",label:"거래처"},{key:"account_code",label:"계정 코드"},{key:"account_name",label:"계정과목"},{key:"account_type",label:"계정 유형"},{key:"department",label:"부서·코스트센터"},{key:"debit",label:"차변",type:"currency"},{key:"credit",label:"대변",type:"currency"},{key:"status",label:"상태"},{key:"created_by",label:"처리자"}] as Column[],rows,total,summary:[{label:"차변 합계",value:round(Number(sums?.debit||0)),format:"currency"},{label:"대변 합계",value:round(Number(sums?.credit||0)),format:"currency"},{label:"매출",value:round(revenue),format:"currency"},{label:"비용",value:round(expense),format:"currency"},{label:"영업 손익",value:round(revenue-expense),format:"currency"}] as SummaryItem[]};
}

async function channelSettlementsReport(db:PmsDatabase,p:Params){
  const where=["s.property_id=pms_current_property_id()","s.business_date BETWEEN ? AND ?"],binds:unknown[]=[p.from,p.to];
  if(p.q){where.push(sqlLike(["c.provider","c.name","r.confirmation_no","s.contract_type","s.status"]));binds.push(...searchBinds(p.q,5));}
  if(p.status){where.push("s.status=?");binds.push(p.status);}if(p.source){where.push("c.provider=?");binds.push(p.source);}
  const from=`FROM channel_settlements s JOIN channel_connections c ON c.id=s.connection_id LEFT JOIN property_channel_settings pcs ON pcs.connection_id=c.id AND pcs.property_id=c.property_id LEFT JOIN reservations r ON r.id=s.reservation_id WHERE ${where.join(" AND ")}`;
  const total=await scalarCount(db,`SELECT COUNT(*) count ${from}`,binds),rows=await pageQuery(db,`SELECT s.business_date,c.provider,c.name channel_name,r.confirmation_no,s.contract_type,s.commission_percent,s.gross_sell_amount,s.channel_cost_amount,s.hotel_net_amount,s.currency,s.due_date,s.status,s.paid_at,s.created_by ${from} ORDER BY s.business_date DESC,COALESCE(pcs.sort_order,9999),s.due_date,c.provider`,binds,p);
  const sums=await db.prepare(`SELECT COALESCE(SUM(s.gross_sell_amount),0) gross,COALESCE(SUM(s.channel_cost_amount),0) cost,COALESCE(SUM(s.hotel_net_amount),0) hotel_net,COALESCE(SUM(CASE WHEN s.status='ACCRUED' THEN s.hotel_net_amount ELSE 0 END),0) receivable ${from}`).bind(...binds).first<Record<string,unknown>>();
  return {columns:[{key:"business_date",label:"발생 영업일",type:"date"},{key:"provider",label:"채널"},{key:"channel_name",label:"연결명"},{key:"confirmation_no",label:"예약번호"},{key:"contract_type",label:"계약 유형"},{key:"commission_percent",label:"수수료율",type:"percent"},{key:"gross_sell_amount",label:"채널 판매가",type:"currency"},{key:"channel_cost_amount",label:"채널 비용",type:"currency"},{key:"hotel_net_amount",label:"호텔 입금가",type:"currency"},{key:"due_date",label:"정산 만기",type:"date"},{key:"status",label:"상태"},{key:"paid_at",label:"지급·입금 시각",type:"datetime"},{key:"created_by",label:"처리자"}] as Column[],rows,total,summary:[{label:"총 판매가",value:round(Number(sums?.gross||0)),format:"currency"},{label:"채널 비용",value:round(Number(sums?.cost||0)),format:"currency"},{label:"호텔 입금가",value:round(Number(sums?.hotel_net||0)),format:"currency"},{label:"정산 대기",value:round(Number(sums?.receivable||0)),format:"currency"}] as SummaryItem[]};
}

async function bookingCurveReport(db:PmsDatabase,p:Params){
  const where=["r.property_id=pms_current_property_id()","(r.created_at AT TIME ZONE prop.timezone)::date BETWEEN ? AND ?"],binds:unknown[]=[p.from,p.to];
  if(p.q){where.push(sqlLike(["r.confirmation_no","g.first_name||' '||g.last_name","r.source","rt.code"]));binds.push(...searchBinds(p.q,4));}
  if(p.status){where.push("r.status=?");binds.push(p.status);}if(p.source){where.push("r.source=?");binds.push(p.source);}if(p.roomTypeId){where.push("r.room_type_id=?");binds.push(p.roomTypeId);}
  const raw=`SELECT (r.created_at AT TIME ZONE prop.timezone)::date booking_date,EXTRACT(HOUR FROM r.created_at AT TIME ZONE prop.timezone) booking_hour,r.status,GREATEST(r.arrival_date-(r.created_at AT TIME ZONE prop.timezone)::date,0) lead_time,COALESCE((SELECT SUM(n.sell_rate) FROM reservation_rate_nights n WHERE n.property_id=r.property_id AND n.reservation_id=r.id),r.nightly_rate*(r.departure_date-r.arrival_date)) revenue FROM reservations r JOIN properties prop ON prop.id=r.property_id JOIN guests g ON g.id=r.guest_id JOIN room_types rt ON rt.id=r.room_type_id WHERE ${where.join(" AND ")}`;
  const grouped=`FROM (${raw}) b GROUP BY booking_date`;
  const total=await scalarCount(db,`SELECT COUNT(*) count FROM (SELECT booking_date ${grouped}) x`,binds);
  const rows=await pageQuery(db,`SELECT booking_date,COUNT(*) FILTER (WHERE booking_hour<6) booked_00_06,COUNT(*) FILTER (WHERE booking_hour>=6 AND booking_hour<12) booked_06_12,COUNT(*) FILTER (WHERE booking_hour>=12 AND booking_hour<18) booked_12_18,COUNT(*) FILTER (WHERE booking_hour>=18) booked_18_24,COUNT(*) total_bookings,COUNT(*) FILTER (WHERE status NOT IN ('CANCELLED','NO_SHOW')) active_bookings,COUNT(*) FILTER (WHERE status='CANCELLED') cancelled_bookings,ROUND(COALESCE(SUM(revenue) FILTER (WHERE status NOT IN ('CANCELLED','NO_SHOW')),0),2) booked_revenue,ROUND(AVG(lead_time),2) avg_lead_time ${grouped} ORDER BY booking_date DESC`,binds,p);
  const sums=await db.prepare(`SELECT COUNT(*) bookings,COUNT(*) FILTER (WHERE status NOT IN ('CANCELLED','NO_SHOW')) active,COALESCE(SUM(revenue) FILTER (WHERE status NOT IN ('CANCELLED','NO_SHOW')),0) revenue,COALESCE(AVG(lead_time),0) lead_time FROM (${raw}) b`).bind(...binds).first<Record<string,unknown>>();
  return {columns:[{key:"booking_date",label:"예약일",type:"date"},{key:"booked_00_06",label:"0–6시",type:"number"},{key:"booked_06_12",label:"6–12시",type:"number"},{key:"booked_12_18",label:"12–18시",type:"number"},{key:"booked_18_24",label:"18–24시",type:"number"},{key:"total_bookings",label:"전체 BOOK",type:"number"},{key:"active_bookings",label:"유효 BOOK",type:"number"},{key:"cancelled_bookings",label:"취소",type:"number"},{key:"booked_revenue",label:"REV",type:"currency"},{key:"avg_lead_time",label:"평균 리드타임",type:"number"}] as Column[],rows,total,summary:[{label:"전체 BOOK",value:Number(sums?.bookings||0),format:"number"},{label:"유효 BOOK",value:Number(sums?.active||0),format:"number"},{label:"REV",value:round(Number(sums?.revenue||0)),format:"currency"},{label:"평균 리드타임",value:round(Number(sums?.lead_time||0)),format:"number"}] as SummaryItem[]};
}

async function channelDepositsReport(db:PmsDatabase,p:Params){
  const where=["s.property_id=pms_current_property_id()","s.due_date BETWEEN ? AND ?"],binds:unknown[]=[p.from,p.to];
  if(p.q){where.push(sqlLike(["c.provider","c.name","cat.display_name","r.confirmation_no","s.deposit_memo","j.entry_no"]));binds.push(...searchBinds(p.q,6));}
  if(p.status){where.push("s.status=?");binds.push(p.status);}if(p.source){where.push("c.provider=?");binds.push(p.source);}
  if(p.scope==="EXCLUDE_ONSITE")where.push("COALESCE(r.payment_type,'CHANNEL')<>'HOTEL' AND COALESCE(cat.integration_mode,'INTEGRATED')<>'MANUAL'");
  const from=`FROM channel_settlements s JOIN channel_connections c ON c.id=s.connection_id LEFT JOIN property_channel_settings pcs ON pcs.connection_id=c.id AND pcs.property_id=c.property_id LEFT JOIN channel_catalog cat ON cat.id=pcs.catalog_id AND cat.property_id=pcs.property_id LEFT JOIN reservations r ON r.id=s.reservation_id LEFT JOIN accounting_journal_entries j ON j.id=s.payment_journal_id WHERE ${where.join(" AND ")}`;
  const total=await scalarCount(db,`SELECT COUNT(*) count ${from}`,binds);
  const rows=await pageQuery(db,`SELECT s.id settlement_id,s.business_date,c.provider,COALESCE(cat.display_name,c.name) channel_name,COALESCE(cat.integration_mode,'INTEGRATED') integration_mode,r.confirmation_no,COALESCE(r.payment_type,'CHANNEL') payment_type,s.contract_type,s.gross_sell_amount,s.channel_cost_amount,s.hotel_net_amount,s.due_date,s.status,s.deposit_date,s.deposit_memo,j.entry_no payment_entry_no,s.paid_at,s.updated_by ${from} ORDER BY CASE WHEN s.status='ACCRUED' THEN 0 ELSE 1 END,s.due_date,COALESCE(pcs.sort_order,9999),c.provider`,binds,p);
  const sums=await db.prepare(`SELECT COALESCE(SUM(s.hotel_net_amount),0) total_net,COALESCE(SUM(s.hotel_net_amount) FILTER (WHERE s.status='ACCRUED'),0) unpaid,COALESCE(SUM(s.hotel_net_amount) FILTER (WHERE s.status='PAID'),0) paid,COUNT(*) FILTER (WHERE s.status='ACCRUED' AND s.due_date<CURRENT_DATE) overdue ${from}`).bind(...binds).first<Record<string,unknown>>();
  return {columns:[{key:"due_date",label:"입금 예정일",type:"date"},{key:"provider",label:"채널 코드"},{key:"channel_name",label:"채널"},{key:"integration_mode",label:"연동 유형"},{key:"confirmation_no",label:"예약번호"},{key:"payment_type",label:"결제 유형"},{key:"contract_type",label:"계약 유형"},{key:"gross_sell_amount",label:"판매가",type:"currency"},{key:"channel_cost_amount",label:"채널 비용",type:"currency"},{key:"hotel_net_amount",label:"입금 예정액",type:"currency"},{key:"status",label:"입금 상태"},{key:"deposit_date",label:"입금일",type:"date"},{key:"deposit_memo",label:"입금 메모"},{key:"payment_entry_no",label:"회계 전표"},{key:"updated_by",label:"처리자"}] as Column[],rows,total,summary:[{label:"입금 대상",value:round(Number(sums?.total_net||0)),format:"currency"},{label:"미입금",value:round(Number(sums?.unpaid||0)),format:"currency"},{label:"입금 완료",value:round(Number(sums?.paid||0)),format:"currency"},{label:"연체 건",value:Number(sums?.overdue||0),format:"number"}] as SummaryItem[]};
}

async function deferredSettlementsReport(db:PmsDatabase,p:Params){
  const where=["i.property_id=pms_current_property_id()","i.issued_date BETWEEN ? AND ?"],binds:unknown[]=[p.from,p.to];
  if(p.q){where.push(sqlLike(["i.invoice_no","a.account_no","a.name","r.confirmation_no","l.memo"]));binds.push(...searchBinds(p.q,5));}if(p.status){where.push("i.status=?");binds.push(p.status);}if(p.source){where.push("a.name=?");binds.push(p.source);}
  const from=`FROM ar_invoices i JOIN ar_accounts a ON a.id=i.ar_account_id JOIN reservations r ON r.id=i.reservation_id LEFT JOIN ar_ledger_entries l ON l.invoice_id=i.id WHERE ${where.join(" AND ")}`;
  const total=await scalarCount(db,`SELECT COUNT(DISTINCT i.id) count ${from}`,binds);
  const rows=await pageQuery(db,`SELECT i.id invoice_id,i.invoice_no,a.account_no,a.name account_name,r.confirmation_no,i.issued_date,i.due_date,i.total,ROUND(COALESCE(SUM(l.credit),0),2) paid,ROUND(COALESCE(SUM(l.debit-l.credit),0),2) balance,i.status,MAX(l.business_date) FILTER (WHERE l.kind='PAYMENT') last_payment_date,CASE WHEN i.status='OPEN' AND i.due_date<?::date THEN ?::date-i.due_date ELSE 0 END days_overdue ${from} GROUP BY i.id,a.id,r.id ORDER BY CASE WHEN i.status='OPEN' THEN 0 ELSE 1 END,i.due_date,i.invoice_no`,[p.to,p.to,...binds],p);
  const sums=await db.prepare(`SELECT COALESCE(SUM(total),0) invoiced,COALESCE(SUM(paid),0) paid,COALESCE(SUM(balance),0) balance,COUNT(*) FILTER (WHERE status='OPEN' AND due_date<?::date) overdue FROM (SELECT i.id,i.total,i.status,i.due_date,COALESCE(SUM(l.credit),0) paid,COALESCE(SUM(l.debit-l.credit),0) balance ${from} GROUP BY i.id) x`).bind(p.to,...binds).first<Record<string,unknown>>();
  return {columns:[{key:"invoice_no",label:"후불 청구서"},{key:"account_no",label:"계정 번호"},{key:"account_name",label:"후불 거래처"},{key:"confirmation_no",label:"예약번호"},{key:"issued_date",label:"발행일",type:"date"},{key:"due_date",label:"정산 만기",type:"date"},{key:"total",label:"청구액",type:"currency"},{key:"paid",label:"수납액",type:"currency"},{key:"balance",label:"미수 잔액",type:"currency"},{key:"status",label:"정산 상태"},{key:"last_payment_date",label:"최종 수납일",type:"date"},{key:"days_overdue",label:"연체일",type:"number"}] as Column[],rows,total,summary:[{label:"후불 청구액",value:round(Number(sums?.invoiced||0)),format:"currency"},{label:"수납액",value:round(Number(sums?.paid||0)),format:"currency"},{label:"미수 잔액",value:round(Number(sums?.balance||0)),format:"currency"},{label:"연체 건",value:Number(sums?.overdue||0),format:"number"}] as SummaryItem[]};
}

async function yoyReport(db:PmsDatabase,p:Params){
  const extra:string[]=[];const binds:unknown[]=[p.from,p.to];
  if(p.q){extra.push(sqlLike(["r.confirmation_no","g.first_name||' '||g.last_name","r.source","rt.code"]));binds.push(...searchBinds(p.q,4));}if(p.source){extra.push("r.source=?");binds.push(p.source);}if(p.roomTypeId){extra.push("r.room_type_id=?");binds.push(p.roomTypeId);}
  const base=`WITH input AS (SELECT ?::date from_date,?::date to_date),months AS (SELECT generate_series(date_trunc('month',from_date),date_trunc('month',to_date),INTERVAL '1 month')::date stay_month FROM input),bookings AS (SELECT date_trunc('month',r.arrival_date)::date arrival_month,COALESCE((SELECT SUM(n.sell_rate) FROM reservation_rate_nights n WHERE n.property_id=r.property_id AND n.reservation_id=r.id),r.nightly_rate*(r.departure_date-r.arrival_date)) revenue FROM reservations r JOIN guests g ON g.id=r.guest_id JOIN room_types rt ON rt.id=r.room_type_id CROSS JOIN input WHERE r.property_id=pms_current_property_id() AND r.arrival_date BETWEEN (input.from_date-INTERVAL '1 year') AND input.to_date AND r.status NOT IN ('CANCELLED','NO_SHOW')${extra.length?` AND ${extra.join(" AND ")}`:""}),series AS (SELECT m.stay_month,COUNT(b.*) FILTER (WHERE b.arrival_month=m.stay_month) current_book,COUNT(b.*) FILTER (WHERE b.arrival_month=(m.stay_month-INTERVAL '1 year')::date) prior_book,COALESCE(SUM(b.revenue) FILTER (WHERE b.arrival_month=m.stay_month),0) current_rev,COALESCE(SUM(b.revenue) FILTER (WHERE b.arrival_month=(m.stay_month-INTERVAL '1 year')::date),0) prior_rev FROM months m LEFT JOIN bookings b ON b.arrival_month IN (m.stay_month,(m.stay_month-INTERVAL '1 year')::date) GROUP BY m.stay_month)`;
  const total=await scalarCount(db,`${base} SELECT COUNT(*) count FROM series`,binds);
  const rows=await pageQuery(db,`${base} SELECT stay_month,current_book,prior_book,ROUND(CASE WHEN prior_book=0 THEN CASE WHEN current_book=0 THEN 0 ELSE 100 END ELSE (current_book-prior_book)*100.0/prior_book END,2) book_yoy,current_rev,prior_rev,ROUND(CASE WHEN prior_rev=0 THEN CASE WHEN current_rev=0 THEN 0 ELSE 100 END ELSE (current_rev-prior_rev)*100.0/prior_rev END,2) rev_yoy FROM series ORDER BY stay_month`,binds,p);
  const sums=await db.prepare(`${base} SELECT COALESCE(SUM(current_book),0) current_book,COALESCE(SUM(prior_book),0) prior_book,COALESCE(SUM(current_rev),0) current_rev,COALESCE(SUM(prior_rev),0) prior_rev FROM series`).bind(...binds).first<Record<string,unknown>>(),currentBook=Number(sums?.current_book||0),priorBook=Number(sums?.prior_book||0),currentRev=Number(sums?.current_rev||0),priorRev=Number(sums?.prior_rev||0);
  return {columns:[{key:"stay_month",label:"입실 월",type:"date"},{key:"current_book",label:"BOOK",type:"number"},{key:"prior_book",label:"전년 BOOK",type:"number"},{key:"book_yoy",label:"BOOK YoY",type:"percent"},{key:"current_rev",label:"REV",type:"currency"},{key:"prior_rev",label:"전년 REV",type:"currency"},{key:"rev_yoy",label:"REV YoY",type:"percent"}] as Column[],rows,total,summary:[{label:"BOOK",value:currentBook,format:"number"},{label:"전년 BOOK",value:priorBook,format:"number"},{label:"BOOK YoY",value:priorBook?round((currentBook-priorBook)*100/priorBook):(currentBook?100:0),format:"percent"},{label:"REV",value:round(currentRev),format:"currency"},{label:"REV YoY",value:priorRev?round((currentRev-priorRev)*100/priorRev):(currentRev?100:0),format:"percent"}] as SummaryItem[]};
}

export async function runReport(db:PmsDatabase,input:URLSearchParams,principal:ReportPrincipal,overrides?:Partial<Params>){
  // Report implementations return rows, total, and summary under identical filters.
  // This dispatcher adds shared metadata and capability flags but never recomputes
  // financial totals from the paginated subset.
  const businessDate=await propertyDate(db);const params=parseParams(input,businessDate,overrides);let result;
  switch(params.report){case"booking_curve":result=await bookingCurveReport(db,params);break;case"occupancy":result=await occupancyReport(db,params);break;case"financials":result=await financialReport(db,params);break;case"accounting_journal":result=await accountingJournalReport(db,params);break;case"channel_settlements":result=await channelSettlementsReport(db,params);break;case"channel_deposits":result=await channelDepositsReport(db,params);break;case"ar":result=await arReport(db,params);break;case"deferred_settlements":result=await deferredSettlementsReport(db,params);break;case"yoy":result=await yoyReport(db,params);break;case"housekeeping":result=await housekeepingReport(db,params);break;case"groups":result=await groupsReport(db,params);break;case"channels":result=await channelsReport(db,params);break;case"audit":result=await auditReport(db,params);break;case"room_inventory":result=await roomInventoryReport(db,params);break;default:result=await reservationsReport(db,params,principal);}
  const definition=reportCatalog.find(item=>item.key===params.report)!;const totalPages=Math.max(1,Math.ceil(result.total/params.pageSize));
  return {catalog:reportCatalog,report:definition,title:definition.label,description:definition.description,generatedAt:new Date().toISOString(),filters:{q:params.q,from:params.from,to:params.to,status:params.status,source:params.source,roomTypeId:params.roomTypeId,scope:params.scope},columns:result.columns,rows:result.rows,summary:result.summary,pagination:{page:params.page,pageSize:params.pageSize,total:result.total,totalPages},export:{allowed:principal.capabilities.includes("REPORT_EXPORT"),maxRows:25000,masked:!principal.capabilities.includes("REPORT_EXPORT")}};
}
