"use client";

/** HotelStory-style available/configured channel catalog and product cutoffs. */
import { useCallback, useEffect, useMemo, useState, type DragEvent } from "react";
import { ListSearch } from "./list-search";
import { usePmsActions } from "./pms-action-context";

type Catalog={id:string;provider_code:string;display_name:string;channel_class:string;integration_mode:"INTEGRATED"|"MANUAL";description:string;sort_order:number;setting_id:string|null;connection_id:string|null;setting_active:boolean|null;setting_sort_order:number|null;supplier_name:string;supplier_code:string;supplier_config:Record<string,unknown>;external_property_id:string;separate_management:boolean;sales_cutoff_days:number;setting_version:number|null;connection_status:string|null;environment:string|null;last_sync_at:string|null};
type Cutoff={id:string;setting_id:string;rate_plan_id:string;cutoff_days:number;cutoff_time:string;active:boolean;version:number;channel_name:string;rate_plan_code:string;rate_plan_name:string};
type RatePlan={id:string;code:string;name:string;active:boolean};
type Connection={id:string;provider:string;external_property_id:string;name:string;status:string};
type Data={catalog:Catalog[];cutoffs:Cutoff[];ratePlans:RatePlan[];connections:Connection[];error?:string};

const modeLabel={INTEGRATED:"연동채널",MANUAL:"자체채널"};
async function fetchData(){const response=await fetch("/api/pms?view=channel_catalog",{cache:"no-store"}),payload=await response.json() as Data;if(!response.ok)throw new Error(payload.error||"채널 카탈로그를 불러오지 못했습니다.");return payload;}

export default function ChannelCatalogManager({canWrite}:{canWrite:boolean}){
  const {act,busy}=usePmsActions(),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[tab,setTab]=useState<"channels"|"cutoffs">("channels"),[editor,setEditor]=useState<Catalog|null>(null),[customOpen,setCustomOpen]=useState(false),[order,setOrder]=useState<string[]>([]);
  const load=useCallback(async()=>{try{setError("");const next=await fetchData();setData(next);setOrder(next.catalog.filter(item=>item.setting_id).sort((a,b)=>Number(a.setting_sort_order)-Number(b.setting_sort_order)).map(item=>String(item.setting_id)));}catch(reason){setError(reason instanceof Error?reason.message:"채널 카탈로그를 불러오지 못했습니다.");}},[]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  const keyword=query.trim().toLocaleLowerCase("ko-KR"),available=useMemo(()=>data?.catalog.filter(item=>!item.setting_id&&(!keyword||`${item.display_name} ${item.provider_code} ${item.description}`.toLocaleLowerCase("ko-KR").includes(keyword)))||[],[data,keyword]),configured=useMemo(()=>{const byId=new Map((data?.catalog||[]).filter(item=>item.setting_id).map(item=>[String(item.setting_id),item]));return order.map(id=>byId.get(id)).filter((item):item is Catalog=>Boolean(item)).filter(item=>!keyword||`${item.display_name} ${item.provider_code} ${item.supplier_name}`.toLocaleLowerCase("ko-KR").includes(keyword));},[data,keyword,order]);
  const move=(id:string,direction:-1|1)=>setOrder(current=>{const index=current.indexOf(id),target=index+direction;if(index<0||target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next;});
  const drop=(event:DragEvent)=>{event.preventDefault();const id=event.dataTransfer.getData("text/channel-catalog"),item=data?.catalog.find(row=>row.id===id&&!row.setting_id);if(item)setEditor(item);};
  return <section className="panel channel-catalog-workspace">
    <div className="channel-catalog-head"><div><p className="eyebrow">SALES CHANNEL CATALOG</p><h2>판매채널 설정</h2><p>사용 가능한 채널을 호텔 판매채널로 등록하고 연동·자체관리, 공급사, 순서와 상품마감을 관리합니다.</p></div><div className="segmented"><button type="button" className={tab==="channels"?"on":""} onClick={()=>setTab("channels")}>채널 설정</button><button type="button" className={tab==="cutoffs"?"on":""} onClick={()=>setTab("cutoffs")}>상품 마감</button></div></div>
    {error&&<div className="report-error" role="alert">{error}<button type="button" onClick={()=>void load()}>다시 시도</button></div>}
    {!data?<div className="module-loading"><b>판매채널을 준비하고 있습니다</b></div>:tab==="channels"?<>
      <div className="channel-catalog-tools"><ListSearch value={query} onChange={setQuery} label="판매채널 검색" placeholder="채널명·코드·공급사" count={available.length+configured.length}/>{canWrite&&<button type="button" className="secondary" onClick={()=>setCustomOpen(true)}>＋ 별도관리 채널</button>}</div>
      <div className="channel-dual-list">
        <section><header><div><h3>채널 설정 가능 목록</h3><p>등록할 채널을 오른쪽으로 이동하세요.</p></div><b>{available.length}</b></header><div className="channel-list-body">{available.map(item=><article key={item.id} draggable={canWrite} onDragStart={event=>event.dataTransfer.setData("text/channel-catalog",item.id)}><div><span className={`channel-mode ${item.integration_mode.toLowerCase()}`}>{modeLabel[item.integration_mode]}</span><b>{item.display_name}</b><small>{item.provider_code} · {item.description}</small></div>{canWrite&&<button type="button" onClick={()=>setEditor(item)}>채널로 설정 →</button>}</article>)}{available.length===0&&<div className="empty-state"><b>추가 가능한 채널이 없습니다</b><p>검색어를 지우거나 별도관리 채널을 등록하세요.</p></div>}</div></section>
        <section className="configured-drop" onDragOver={event=>event.preventDefault()} onDrop={drop}><header><div><h3>채널 설정 목록</h3><p>드래그 또는 화살표로 노출 순서를 정합니다.</p></div><b>{configured.length}</b></header><div className="channel-list-body">{configured.map((item,index)=><article className={item.setting_active?"":"inactive"} key={item.setting_id} draggable={canWrite} onDragStart={event=>event.dataTransfer.setData("text/channel-setting",String(item.setting_id))} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();const source=event.dataTransfer.getData("text/channel-setting");if(!source||source===item.setting_id)return;setOrder(current=>{const next=current.filter(id=>id!==source),target=next.indexOf(String(item.setting_id));next.splice(target,0,source);return next;});}}><div className="channel-order-controls">{canWrite&&<><button type="button" aria-label={`${item.display_name} 위로`} disabled={index===0} onClick={()=>move(String(item.setting_id),-1)}>↑</button><button type="button" aria-label={`${item.display_name} 아래로`} disabled={index===configured.length-1} onClick={()=>move(String(item.setting_id),1)}>↓</button></>}</div><div><span className={`channel-mode ${item.integration_mode.toLowerCase()}`}>{modeLabel[item.integration_mode]}</span><b>{item.display_name}</b><small>{item.supplier_name||"공급사 미설정"} · {item.connection_status||"수기 관리"} · D-{item.sales_cutoff_days}</small></div>{canWrite&&<div className="channel-row-actions"><button type="button" onClick={()=>setEditor(item)}>수정</button><button type="button" disabled={Boolean(busy)} onClick={async()=>{if(await act("set_property_channel_active",{settingId:String(item.setting_id),active:String(!item.setting_active),expectedVersion:String(item.setting_version)}))await load()}}>{item.setting_active?"사용안함":"사용함"}</button><button type="button" className="danger" disabled={Boolean(busy)} onClick={async()=>{if(window.confirm(`${item.display_name} 설정을 삭제할까요?`)&&await act("delete_property_channel",{settingId:String(item.setting_id)}))await load()}}>삭제</button></div>}</article>)}{configured.length===0&&<div className="empty-state drop-hint"><b>설정된 채널이 없습니다</b><p>왼쪽 채널을 드래그하거나 ‘채널로 설정’을 누르세요.</p></div>}</div>{canWrite&&configured.length>0&&<footer><span>현재 순서가 리포트와 채널 화면에 함께 반영됩니다.</span><button type="button" className="primary" disabled={Boolean(busy)} onClick={async()=>{if(await act("reorder_property_channels",{settingIds:JSON.stringify(order)}))await load()}}>채널순서저장</button></footer>}</section>
      </div>
    </>:<ChannelCutoffPanel data={data} canWrite={canWrite} reload={load}/>}
    {editor&&<ChannelSettingDialog item={editor} connections={data?.connections||[]} close={()=>setEditor(null)} saved={async()=>{setEditor(null);await load()}}/>}
    {customOpen&&<CustomChannelDialog close={()=>setCustomOpen(false)} saved={async()=>{setCustomOpen(false);await load()}}/>}
  </section>;
}

function ChannelSettingDialog({item,connections,close,saved}:{item:Catalog;connections:Connection[];close:()=>void;saved:()=>Promise<void>}){
  const {act,busy}=usePmsActions(),matching=connections.filter(connection=>connection.provider===item.provider_code),[form,setForm]=useState({connectionId:item.connection_id||matching[0]?.id||"",externalPropertyId:item.external_property_id||"",supplierName:item.supplier_name||"",supplierCode:item.supplier_code||"",supplierConfig:JSON.stringify(item.supplier_config||{},null,2),salesCutoffDays:String(item.sales_cutoff_days||0),sortOrder:String(item.setting_sort_order??item.sort_order),separateManagement:String(Boolean(item.separate_management)),active:String(item.setting_active!==false)}),set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&close()}><form className="booking-modal channel-setting-dialog" role="dialog" aria-modal="true" aria-label={`${item.display_name} 채널 설정`} onSubmit={async event=>{event.preventDefault();if(await act("configure_property_channel",{catalogId:item.id,...form,...(item.setting_id?{expectedVersion:String(item.setting_version)}:{})}))await saved()}}><div className="drawer-head"><div><p>{item.provider_code} · {modeLabel[item.integration_mode]}</p><h2>{item.display_name} 설정</h2></div><button type="button" onClick={close} aria-label="닫기">×</button></div><p className="form-intro">연동채널은 연결 상태가 ARI 전송 대상에 즉시 반영됩니다. 자체채널은 PMS 재고·리포트 분류만 사용합니다.</p><div className="form-grid">{item.integration_mode==="INTEGRATED"&&<><label><span>기존 연결</span><select value={form.connectionId} onChange={event=>set("connectionId",event.target.value)}><option value="">새 연결 생성</option>{matching.map(connection=><option value={connection.id} key={connection.id}>{connection.name} · {connection.status}</option>)}</select></label><label><span>외부 호텔 ID</span><input required={!form.connectionId} maxLength={120} value={form.externalPropertyId} onChange={event=>set("externalPropertyId",event.target.value)}/></label></>}<label><span>서플라이어명</span><input maxLength={100} value={form.supplierName} onChange={event=>set("supplierName",event.target.value)}/></label><label><span>서플라이어 코드</span><input maxLength={100} value={form.supplierCode} onChange={event=>set("supplierCode",event.target.value)}/></label><label><span>기본 판매 마감 (D-n)</span><input type="number" min="0" max="730" value={form.salesCutoffDays} onChange={event=>set("salesCutoffDays",event.target.value)}/></label><label><span>채널 순서</span><input type="number" min="0" max="9999" value={form.sortOrder} onChange={event=>set("sortOrder",event.target.value)}/></label><label className="span-2"><span>서플라이어 설정 (JSON)</span><textarea spellCheck={false} value={form.supplierConfig} onChange={event=>set("supplierConfig",event.target.value)}/></label></div><div className="channel-setting-switches"><label><input type="checkbox" checked={form.active==="true"} onChange={event=>set("active",String(event.target.checked))}/><span>사용함</span></label><label><input type="checkbox" checked={form.separateManagement==="true"} onChange={event=>set("separateManagement",String(event.target.checked))}/><span>별도관리 채널</span></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>취소</button><button className="primary" disabled={Boolean(busy)}>{busy?"저장 중…":"채널 설정 저장"}</button></div></form></div>;
}

function CustomChannelDialog({close,saved}:{close:()=>void;saved:()=>Promise<void>}){const {act,busy}=usePmsActions(),[form,setForm]=useState({providerCode:"",displayName:"",channelClass:"OTHER",integrationMode:"MANUAL",description:"",sortOrder:"900"}),set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));return <div className="modal-backdrop"><form className="booking-modal" onSubmit={async event=>{event.preventDefault();if(await act("upsert_channel_catalog",form))await saved()}}><div className="drawer-head"><div><p>SEPARATE CHANNEL</p><h2>별도관리 채널 등록</h2></div><button type="button" onClick={close}>×</button></div><div className="form-grid"><label><span>채널 코드</span><input required pattern="[A-Z0-9_]{2,40}" value={form.providerCode} onChange={event=>set("providerCode",event.target.value.toUpperCase())}/></label><label><span>채널명</span><input required maxLength={100} value={form.displayName} onChange={event=>set("displayName",event.target.value)}/></label><label><span>분류</span><select value={form.channelClass} onChange={event=>set("channelClass",event.target.value)}><option value="OTA">OTA</option><option value="META">메타검색</option><option value="DIRECT">자체 판매</option><option value="WHOLESALE">도매/B2B</option><option value="OTHER">기타</option></select></label><label><span>관리 방식</span><select value={form.integrationMode} onChange={event=>set("integrationMode",event.target.value)}><option value="MANUAL">자체채널 · 수기</option><option value="INTEGRATED">연동채널 · ARI</option></select></label><label className="span-2"><span>설명</span><textarea maxLength={500} value={form.description} onChange={event=>set("description",event.target.value)}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>취소</button><button className="primary" disabled={Boolean(busy)}>목록에 등록</button></div></form></div>}

function ChannelCutoffPanel({data,canWrite,reload}:{data:Data;canWrite:boolean;reload:()=>Promise<void>}){const {act,busy}=usePmsActions(),settings=data.catalog.filter(item=>item.setting_id),[form,setForm]=useState({settingId:String(settings[0]?.setting_id||""),ratePlanId:String(data.ratePlans.find(plan=>plan.active)?.id||""),cutoffDays:"0",cutoffTime:"23:59",active:"true"}),set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));return <div className="channel-cutoff-layout">{canWrite&&<form className="channel-cutoff-form" onSubmit={async event=>{event.preventDefault();if(await act("upsert_channel_product_cutoff",form))await reload()}}><div><h3>상품마감설정</h3><p>채널·판매상품별 D-n 마감 시각을 지정합니다.</p></div><label><span>채널</span><select value={form.settingId} onChange={event=>set("settingId",event.target.value)}>{settings.map(item=><option value={String(item.setting_id)} key={item.setting_id}>{item.display_name}</option>)}</select></label><label><span>판매 상품</span><select value={form.ratePlanId} onChange={event=>set("ratePlanId",event.target.value)}>{data.ratePlans.filter(plan=>plan.active).map(plan=><option value={plan.id} key={plan.id}>{plan.code} · {plan.name}</option>)}</select></label><label><span>체크인 D-n</span><input type="number" min="0" max="730" value={form.cutoffDays} onChange={event=>set("cutoffDays",event.target.value)}/></label><label><span>마감 시각</span><input type="time" value={form.cutoffTime} onChange={event=>set("cutoffTime",event.target.value)}/></label><label className="inline-check"><input type="checkbox" checked={form.active==="true"} onChange={event=>set("active",String(event.target.checked))}/><span>활성</span></label><button className="primary" disabled={Boolean(busy)||!form.settingId||!form.ratePlanId}>상품 마감 저장</button></form>}<section className="channel-cutoff-list"><header><h3>적용 중인 상품 마감</h3><b>{data.cutoffs.length}</b></header>{data.cutoffs.map(item=><article key={item.id}><div><b>{item.channel_name}</b><span>{item.rate_plan_code} · {item.rate_plan_name}</span></div><strong>D-{item.cutoff_days} · {String(item.cutoff_time).slice(0,5)}</strong><i className={`status ${item.active?"ready":""}`}>{item.active?"ACTIVE":"OFF"}</i>{canWrite&&<button type="button" className="danger" disabled={Boolean(busy)} onClick={async()=>{if(window.confirm("이 상품 마감 설정을 삭제할까요?")&&await act("delete_channel_product_cutoff",{cutoffId:item.id}))await reload()}}>삭제</button>}</article>)}{data.cutoffs.length===0&&<div className="empty-state"><b>상품별 마감 설정이 없습니다</b><p>채널 기본 마감일이 적용됩니다.</p></div>}</section></div>}
