"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Reservation = { id:string; confirmation_no:string; first_name:string; last_name:string; vip_level:string; room_number:string|null; room_type_code:string; room_type_name:string; arrival_date:string; departure_date:string; status:string; source:string; rate_plan:string; eta:string|null; notes:string; balance:number };
type Room = { id:string; number:string; floor:number; room_type_id:string; room_type_code:string; room_type_name:string; front_desk_status:string; housekeeping_status:string; task_status:string|null; assignee:string|null };
type Data = { property:{name:string;business_date:string;currency:string}; reservations:Reservation[]; rooms:Room[]; metrics:{rooms:number;occupied:number;dirty:number;ready:number} };

const money = (n:number) => new Intl.NumberFormat("ko-KR", { style:"currency", currency:"KRW", maximumFractionDigits:0 }).format(n);
const labels:Record<string,string> = { DUE_IN:"도착 예정", IN_HOUSE:"투숙 중", CHECKED_OUT:"체크아웃", CLEAN:"청소 완료", INSPECTED:"점검 완료", DIRTY:"청소 필요", OUT_OF_SERVICE:"판매 중지", VACANT:"공실", OCCUPIED:"재실" };

export default function PMS() {
  const [data,setData] = useState<Data|null>(null); const [error,setError] = useState(""); const [busy,setBusy] = useState("");
  const [section,setSection] = useState("overview"); const [selected,setSelected] = useState<Reservation|null>(null); const [query,setQuery] = useState(""); const [roomFilter,setRoomFilter] = useState("ALL");
  const [newBooking,setNewBooking] = useState(false);
  const load = useCallback(async()=>{ try { const r=await fetch("/api/pms",{cache:"no-store"}); const j=await r.json(); if(!r.ok) throw new Error(j.error); setData(j); } catch(e){setError(e instanceof Error?e.message:"데이터를 불러오지 못했습니다.");}},[]);
  // The first render intentionally hydrates the live operational snapshot.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{load();},[load]);
  async function act(action:string, payload:Record<string,string>={}) { setBusy(action); setError(""); try { const r=await fetch("/api/pms",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({action,...payload})}); const j=await r.json(); if(!r.ok) throw new Error(j.error); setData(j); if(selected) setSelected(j.reservations.find((x:Reservation)=>x.id===selected.id)||null); return true; } catch(e){setError(e instanceof Error?e.message:"작업을 완료하지 못했습니다."); return false;} finally{setBusy("");} }
  const reservations = useMemo(()=>data?.reservations.filter(r=>`${r.first_name} ${r.last_name} ${r.confirmation_no} ${r.room_number}`.toLowerCase().includes(query.toLowerCase()))??[],[data,query]);
  const arrivalCount = data?.reservations.filter(r=>r.status==="DUE_IN").length??0; const inHouse = data?.reservations.filter(r=>r.status==="IN_HOUSE").length??0;
  const occupancy = data ? Math.round(Number(data.metrics.occupied)/Number(data.metrics.rooms)*100) : 0;
  if(!data) return <main className="loading"><div className="brand-mark">A</div><p>AURORA PMS를 준비하고 있습니다</p>{error&&<button onClick={load}>다시 시도</button>}</main>;
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">A</span><span><b>AURORA</b><small>HOTEL OS</small></span></div>
      <nav aria-label="주 메뉴">
        {[['overview','⌂','오퍼레이션'],['frontdesk','⇄','프런트 데스크'],['rooms','▦','룸 & 하우스키핑'],['revenue','↗','매출 & 인사이트'],['audit','✓','야간 감사']].map(([id,icon,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><i>{icon}</i>{label}{id==='frontdesk'&&<em>{arrivalCount}</em>}</button>)}
      </nav>
      <div className="sidebar-bottom"><div className="system-ok"><span/> 모든 시스템 정상</div><button className="profile"><span>JK</span><div><b>정지훈</b><small>프런트 매니저</small></div><i>•••</i></button></div>
    </aside>
    <main className="workspace">
      <header><div><p className="eyebrow">{data.property.name} · 영업일 {data.property.business_date}</p><h1>{section==='overview'?'오늘의 오퍼레이션':section==='frontdesk'?'프런트 데스크':section==='rooms'?'룸 & 하우스키핑':section==='revenue'?'매출 & 인사이트':'야간 감사'}</h1></div><div className="header-actions"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="고객, 예약번호, 객실 검색"/><kbd>⌘ K</kbd></label><button className="icon-btn" aria-label="알림">♢<b>3</b></button><button className="primary" onClick={()=>setNewBooking(true)}>＋ 새 예약</button></div></header>
      {error&&<div className="toast" role="alert"><span>!</span>{error}<button onClick={()=>setError('')}>×</button></div>}
      {section==='overview'&&<>
        <section className="pulse-grid">
          <article><div className="metric-head"><span className="metric-icon blue">⇲</span><small>오늘 도착</small><b className="trend up">+8%</b></div><strong>{arrivalCount}<small>건</small></strong><p><b>{data.reservations.filter(r=>r.status==='DUE_IN'&&r.room_number).length}</b> 객실 배정 완료</p></article>
          <article><div className="metric-head"><span className="metric-icon green">●</span><small>현재 투숙</small><b className="trend">실시간</b></div><strong>{inHouse}<small>건</small></strong><p>VIP 고객 <b>{data.reservations.filter(r=>r.status==='IN_HOUSE'&&r.vip_level!=='NONE').length}</b>명 포함</p></article>
          <article><div className="metric-head"><span className="metric-icon violet">◫</span><small>점유율</small><b className="trend up">▲ 4.2%</b></div><strong>{occupancy}<small>%</small></strong><div className="progress"><i style={{width:`${occupancy}%`}}/></div></article>
          <article><div className="metric-head"><span className="metric-icon amber">₩</span><small>예상 객실 매출</small><b className="trend up">+12.4%</b></div><strong className="revenue">₩1.04M</strong><p>ADR <b>₩261,000</b></p></article>
        </section>
        <div className="two-col">
          <section className="panel arrivals"><div className="panel-title"><div><h2>도착 플로우</h2><p>ETA 순 · 즉시 처리 가능한 예약</p></div><button onClick={()=>setSection('frontdesk')}>전체 보기 →</button></div>
            <div className="flow-head"><span>고객</span><span>객실</span><span>ETA</span><span>상태</span><span/></div>
            {reservations.filter(r=>r.status==='DUE_IN').slice(0,4).map(r=><button className="flow-row" key={r.id} onClick={()=>setSelected(r)}><span className="guest"><i>{r.first_name[0]}{r.last_name[0]}</i><span><b>{r.first_name} {r.last_name}</b><small>{r.confirmation_no} · {r.source}</small></span>{r.vip_level!=='NONE'&&<em>{r.vip_level}</em>}</span><span><b>{r.room_number||'미배정'}</b><small>{r.room_type_code}</small></span><span>{r.eta||'미정'}</span><span><i className={`status ${r.room_number?'ready':'warn'}`}>{r.room_number?'체크인 준비':'배정 필요'}</i></span><span className="more">›</span></button>)}
          </section>
          <section className="panel room-pulse"><div className="panel-title"><div><h2>객실 준비 현황</h2><p>프런트·하우스키핑 동기화</p></div><span className="live">● LIVE</span></div>
            <div className="donut-wrap"><div className="donut" style={{background:`conic-gradient(#20a474 0 ${Number(data.metrics.ready)/Number(data.metrics.rooms)*100}%, #f0a436 0 ${(Number(data.metrics.ready)+Number(data.metrics.dirty))/Number(data.metrics.rooms)*100}%, #dfe4e8 0)`}}><div><strong>{data.metrics.ready}</strong><small>판매 가능</small></div></div><div className="legend"><p><i className="dot clean"/><span>청소/점검 완료</span><b>{data.metrics.ready}</b></p><p><i className="dot dirty"/><span>청소 필요</span><b>{data.metrics.dirty}</b></p><p><i className="dot oos"/><span>판매 중지</span><b>{data.rooms.filter(r=>r.housekeeping_status==='OUT_OF_SERVICE').length}</b></p></div></div>
            <button className="secondary wide" onClick={()=>setSection('rooms')}>하우스키핑 보드 열기</button>
          </section>
        </div>
        <section className="insight-strip"><span>✦</span><div><b>오로라 인사이트</b><p>15:00–17:00에 도착이 집중됩니다. 현재 미배정 1건과 청소 중 1실을 우선 처리하면 평균 체크인 대기시간을 줄일 수 있어요.</p></div><button onClick={()=>setSection('rooms')}>실행 계획 보기</button></section>
      </>}
      {section==='frontdesk'&&<section className="panel full"><div className="panel-title"><div><h2>예약 & 투숙객</h2><p>도착, 재실, 출발 업무를 하나의 큐에서 처리합니다</p></div><div className="segmented"><button className="on">전체 {reservations.length}</button><button>도착 {arrivalCount}</button><button>재실 {inHouse}</button></div></div>
        <div className="reservation-table"><div className="table-head"><span>고객 / 예약</span><span>숙박</span><span>객실</span><span>채널</span><span>잔액</span><span>상태</span></div>{reservations.map(r=><button key={r.id} className="table-row" onClick={()=>setSelected(r)}><span className="guest"><i>{r.first_name[0]}{r.last_name[0]}</i><span><b>{r.first_name} {r.last_name}</b><small>{r.confirmation_no}</small></span></span><span><b>{r.arrival_date.slice(5)} → {r.departure_date.slice(5)}</b><small>{r.eta&&`ETA ${r.eta}`}</small></span><span><b>{r.room_number||'미배정'}</b><small>{r.room_type_name}</small></span><span>{r.source}</span><span className={Number(r.balance)>0?'due':''}>{money(Number(r.balance))}</span><span><i className={`status ${r.status==='IN_HOUSE'?'stay':r.status==='DUE_IN'?'ready':''}`}>{labels[r.status]}</i></span></button>)}</div>
      </section>}
      {section==='rooms'&&<section className="panel full"><div className="panel-title"><div><h2>라이브 룸 랙</h2><p>객실 상태 변경은 프런트와 하우스키핑에 즉시 반영됩니다</p></div><div className="segmented">{['ALL','DIRTY','CLEAN','INSPECTED'].map(f=><button className={roomFilter===f?'on':''} onClick={()=>setRoomFilter(f)} key={f}>{f==='ALL'?'전체':labels[f]}</button>)}</div></div><div className="room-grid">{data.rooms.filter(r=>roomFilter==='ALL'||r.housekeeping_status===roomFilter).map(r=><article className={`room-card ${r.housekeeping_status.toLowerCase()}`} key={r.id}><div><span>{r.room_type_code}</span><i className={`dot ${r.housekeeping_status.toLowerCase()}`}/></div><strong>{r.number}</strong><p>{r.room_type_name}</p><div className="room-status"><b>{labels[r.housekeeping_status]}</b><small>{labels[r.front_desk_status]}{r.assignee&&` · ${r.assignee}`}</small></div>{r.housekeeping_status==='DIRTY'&&<button disabled={!!busy} onClick={()=>act('housekeeping',{roomId:r.id,status:'CLEAN'})}>청소 완료 처리</button>}{r.housekeeping_status==='CLEAN'&&<button disabled={!!busy} onClick={()=>act('housekeeping',{roomId:r.id,status:'INSPECTED'})}>점검 완료 처리</button>}</article>)}</div></section>}
      {section==='revenue'&&<Revenue/>} {section==='audit'&&<Audit data={data}/>} 
    </main>
    {selected&&<ReservationDrawer r={selected} busy={busy} close={()=>setSelected(null)} act={act}/>} 
    {newBooking&&<NewReservation rooms={data.rooms} busy={busy} close={()=>setNewBooking(false)} act={act}/>} 
  </div>;
}

function ReservationDrawer({r,busy,close,act}:{r:Reservation;busy:string;close:()=>void;act:(a:string,p:Record<string,string>)=>Promise<boolean>}) { const [amount,setAmount]=useState(String(Math.max(0,Number(r.balance)))); const [charge,setCharge]=useState(""); return <div className="drawer-backdrop" onMouseDown={e=>e.currentTarget===e.target&&close()}><aside className="drawer" aria-label="예약 상세"><div className="drawer-head"><div><p>{r.confirmation_no}</p><h2>{r.first_name} {r.last_name}</h2></div><button onClick={close}>×</button></div><div className="guest-hero"><span>{r.first_name[0]}{r.last_name[0]}</span><div><b>{r.vip_level==='NONE'?'일반 고객':`${r.vip_level} 멤버`}</b><p>{r.source} · {r.rate_plan}</p></div><i className={`status ${r.status==='IN_HOUSE'?'stay':'ready'}`}>{labels[r.status]}</i></div><dl><div><dt>숙박 일정</dt><dd>{r.arrival_date} → {r.departure_date}</dd></div><div><dt>객실</dt><dd>{r.room_number||'미배정'} · {r.room_type_name}</dd></div><div><dt>도착 예정</dt><dd>{r.eta||'미정'}</dd></div></dl>{r.notes&&<div className="note"><b>직원 메모</b><p>{r.notes}</p></div>}<div className="folio"><div><h3>폴리오 잔액</h3><strong>{money(Number(r.balance))}</strong></div>{r.status==='IN_HOUSE'&&<div className="payment"><input aria-label="전기 금액" placeholder="추가 비용" value={charge} onChange={e=>setCharge(e.target.value)}/><button disabled={!!busy||!charge} onClick={()=>act('post_charge',{reservationId:r.id,amount:charge,code:'MISC',description:'기타 매출'}).then(ok=>ok&&setCharge(''))}>비용 전기</button></div>}{Number(r.balance)>0&&<div className="payment"><input aria-label="결제 금액" value={amount} onChange={e=>setAmount(e.target.value)}/><button disabled={!!busy} onClick={()=>act('post_payment',{reservationId:r.id,amount,method:'CARD'})}>카드 결제</button></div>}</div><div className="drawer-actions">{r.status==='DUE_IN'&&<button className="primary wide" disabled={!!busy} onClick={()=>act('check_in',{reservationId:r.id})}>{busy?'처리 중…':'체크인 완료'}</button>}{r.status==='IN_HOUSE'&&<button className="primary wide" disabled={!!busy||Number(r.balance)!==0} onClick={()=>act('check_out',{reservationId:r.id})}>{Number(r.balance)!==0?'잔액 정산 필요':'체크아웃 완료'}</button>}<button className="secondary wide">예약 전체 보기</button></div></aside></div> }

function NewReservation({rooms,busy,close,act}:{rooms:Room[];busy:string;close:()=>void;act:(a:string,p:Record<string,string>)=>Promise<boolean>}) {
  const types=Array.from(new Map(rooms.map(r=>[r.room_type_id,{id:r.room_type_id,code:r.room_type_code,name:r.room_type_name}])).values()); const [form,setForm]=useState({firstName:"",lastName:"",email:"",phone:"",arrivalDate:"2026-07-15",departureDate:"2026-07-16",roomTypeId:types[0]?.id||"",roomId:"",adults:"2",children:"0",source:"Direct",ratePlan:"BAR",nightlyRate:"",eta:"15:00"});
  const set=(key:string,value:string)=>setForm(v=>({...v,[key]:value})); const available=rooms.filter(r=>r.room_type_id===form.roomTypeId&&r.front_desk_status==='VACANT'&&['CLEAN','INSPECTED'].includes(r.housekeeping_status));
  return <div className="modal-backdrop"><form className="booking-modal" onSubmit={async e=>{e.preventDefault();if(await act('create_reservation',form))close()}}><div className="drawer-head"><div><p>NEW RESERVATION</p><h2>새 예약 만들기</h2></div><button type="button" onClick={close}>×</button></div><p className="form-intro">고객, 일정, 객실을 한 번에 확정합니다. 객실을 선택하면 박 단위 재고가 즉시 잠깁니다.</p><div className="form-grid"><label><span>이름</span><input required value={form.firstName} onChange={e=>set('firstName',e.target.value)}/></label><label><span>성</span><input required value={form.lastName} onChange={e=>set('lastName',e.target.value)}/></label><label><span>이메일</span><input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label><span>연락처</span><input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label><span>도착일</span><input type="date" required value={form.arrivalDate} onChange={e=>set('arrivalDate',e.target.value)}/></label><label><span>출발일</span><input type="date" required value={form.departureDate} onChange={e=>set('departureDate',e.target.value)}/></label><label><span>객실 타입</span><select value={form.roomTypeId} onChange={e=>{set('roomTypeId',e.target.value);set('roomId','')}}>{types.map(t=><option key={t.id} value={t.id}>{t.code} · {t.name}</option>)}</select></label><label><span>객실 배정</span><select value={form.roomId} onChange={e=>set('roomId',e.target.value)}><option value="">나중에 배정</option>{available.map(r=><option key={r.id} value={r.id}>{r.number} · {labels[r.housekeeping_status]}</option>)}</select></label><label><span>예약 채널</span><select value={form.source} onChange={e=>set('source',e.target.value)}><option>Direct</option><option>Booking.com</option><option>Expedia</option><option>Corporate</option></select></label><label><span>도착 예정</span><input type="time" value={form.eta} onChange={e=>set('eta',e.target.value)}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>취소</button><button className="primary" disabled={!!busy}>{busy?'예약 확인 중…':'예약 확정'}</button></div></form></div>
}

function Revenue() { return <div className="two-col revenue-layout"><section className="panel"><div className="panel-title"><div><h2>7일 객실 매출</h2><p>영업일 기준 · 순매출</p></div><b className="trend up">+12.4% vs 지난주</b></div><div className="chart">{[42,58,46,72,62,88,78].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><span>{10+i}일</span></div>)}</div></section><section className="panel"><div className="panel-title"><div><h2>채널 믹스</h2><p>예약 생산 비중</p></div></div><div className="channel-list">{[['Direct',38,'#194d45'],['Booking.com',27,'#4176d8'],['Corporate',21,'#8d6ccf'],['Expedia',14,'#eba43c']].map(([n,v,c])=><div key={String(n)}><p><span><i style={{background:String(c)}}/>{n}</span><b>{v}%</b></p><div><i style={{width:`${v}%`,background:String(c)}}/></div></div>)}</div></section></div> }
function Audit({data}:{data:Data}) { const checks=[['미처리 도착 예약',data.reservations.filter(r=>r.status==='DUE_IN').length,'확인 필요'],['미결제 재실 폴리오',data.reservations.filter(r=>r.status==='IN_HOUSE'&&Number(r.balance)>0).length,'확인 필요'],['판매 중지 객실',data.rooms.filter(r=>r.housekeeping_status==='OUT_OF_SERVICE').length,'참고'],['인터페이스 동기화 오류',0,'정상']]; return <section className="panel full audit"><div className="panel-title"><div><h2>영업일 마감 컨트롤</h2><p>{data.property.business_date} · 선행 검증이 완료되어야 날짜를 마감할 수 있습니다</p></div><span className="audit-score">{checks.filter(x=>Number(x[1])===0).length}/{checks.length} 통과</span></div>{checks.map(([name,count,state])=><div className="audit-row" key={String(name)}><span className={Number(count)===0?'pass':'attention'}>{Number(count)===0?'✓':'!'}</span><div><b>{name}</b><small>{state}</small></div><strong>{count}{typeof count==='number'?'건':''}</strong><button>{Number(count)===0?'완료':'검토'}</button></div>)}<button className="primary audit-run" disabled>모든 항목 확인 후 영업일 마감</button></section> }
