"use client";

/** HotelStory-compatible voucher preview and delivery controls. */
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { formatMoney } from "../lib/format";
import { usePmsActions } from "./pms-action-context";

type Voucher={language:"KO"|"EN";amountVisible:boolean;hotel:{name:string;currency:string;address:string;phone:string;email:string;checkinTime:string;checkoutTime:string};reservation:{confirmationNo:string;bookerName:string;bookerEmail:string;guestName:string;guestEmail:string;guestPhone:string;arrivalDate:string;departureDate:string;nights:number;roomType:string;roomNumber:string;productName:string;productCode:string;adults:number;children:number;guestRequest:string;inclusions:string[];cancellationPolicy:string;cancellationTerms:Array<{basis?:string;feePercent?:number}>};rateNights:Array<{stayDate:string;rate:number;ratePlan:string}>;totalAmount:number;error?:string};
type Props={reservationId:string;confirmationNo:string;defaultEmail:string;canExport:boolean;close:()=>void};

export default function ReservationVoucherDialog({reservationId,confirmationNo,defaultEmail,canExport,close}:Props){
  const {busy,act}=usePmsActions();
  const [language,setLanguage]=useState<"KO"|"EN">("KO"),[showAmount,setShowAmount]=useState(true),[recipientEmail,setRecipientEmail]=useState(defaultEmail),[subject,setSubject]=useState(`[${confirmationNo}] 예약 확인서`);
  const params=new URLSearchParams({view:"reservation_voucher",reservationId,language,showAmount:String(showAmount)}),baseUrl=`/api/pms?${params.toString()}`;
  const query=useQuery({queryKey:["pms","reservation-voucher",reservationId,language,showAmount],queryFn:async()=>{const response=await fetch(baseUrl,{cache:"no-store"}),payload=await response.json() as Voucher;if(!response.ok)throw new Error(payload.error||"예약 확인서를 불러오지 못했습니다.");return payload;},staleTime:10_000});
  const changeLanguage=(next:"KO"|"EN")=>{setLanguage(next);setSubject(next==="EN"?`[${confirmationNo}] Booking Confirmation`:`[${confirmationNo}] 예약 확인서`);};
  const openDocument=(format:"pdf"|"xlsx"|"html")=>{const url=`${baseUrl}&format=${format}`;if(format==="html")window.open(url,"_blank","noopener,noreferrer");else{const anchor=document.createElement("a");anchor.href=url;anchor.download="";document.body.appendChild(anchor);anchor.click();anchor.remove();}};
  const queue=async()=>{if(await act("queue_reservation_voucher",{reservationId,language,showAmount:String(showAmount),recipientEmail,subject}))close();};
  const data=query.data,l=language==="EN"?{title:"Booking Confirmation",guest:"Guest",booker:"Booker",stay:"Stay",room:"Room",product:"Rate product",rates:"Nightly rates",policy:"Cancellation policy",total:"Total amount",send:"Queue email",recipient:"Recipient",subject:"Subject"}:{title:"예약 확인서",guest:"투숙객",booker:"예약자",stay:"숙박 일정",room:"객실",product:"예약 상품",rates:"일자별 요금",policy:"취소 규정",total:"총 결제 예정액",send:"메일 발송 예약",recipient:"수신자",subject:"제목"};
  return <div className="modal-backdrop voucher-modal-backdrop"><section className="voucher-dialog" role="dialog" aria-modal="true" aria-label={l.title}>
    <div className="drawer-head"><div><p>{confirmationNo} · DOCUMENT</p><h2>{l.title}</h2></div><button type="button" aria-label="닫기" onClick={close}>×</button></div>
    <div className="voucher-controls"><div className="segmented" aria-label="확인서 언어"><button type="button" className={language==="KO"?"on":""} onClick={()=>changeLanguage("KO")}>한국어</button><button type="button" className={language==="EN"?"on":""} onClick={()=>changeLanguage("EN")}>English</button></div><label className="voucher-amount-toggle"><input type="checkbox" checked={showAmount} onChange={event=>setShowAmount(event.target.checked)}/><span>금액 표시</span></label></div>
    {query.isLoading&&<div className="reservation-detail-state"><b>확인서를 만들고 있습니다</b><p>예약 시점의 상품·요금·취소규정을 불러오고 있어요.</p></div>}
    {query.error&&<div className="report-error" role="alert">{query.error instanceof Error?query.error.message:"확인서를 불러오지 못했습니다."}</div>}
    {data&&<div className="voucher-preview"><header><div><small>{data.hotel.name}</small><h3>{l.title}</h3></div><strong>{data.reservation.confirmationNo}</strong></header><div className="voucher-facts"><div><span>{l.guest}</span><b>{data.reservation.guestName}</b></div><div><span>{l.booker}</span><b>{data.reservation.bookerName}</b></div><div><span>{l.stay}</span><b>{data.reservation.arrivalDate} → {data.reservation.departureDate} · {data.reservation.nights}박</b></div><div><span>{l.room}</span><b>{data.reservation.roomType} · {data.reservation.roomNumber||"미배정"}</b></div><div><span>{l.product}</span><b>{data.reservation.productName} · {data.reservation.productCode}</b></div><div><span>Check-in / out</span><b>{data.hotel.checkinTime} / {data.hotel.checkoutTime}</b></div></div><h4>{l.rates}</h4><div className="voucher-rate-list">{data.rateNights.map(night=><div key={night.stayDate}><span>{night.stayDate}</span><span>{night.ratePlan}</span>{showAmount&&<b>{formatMoney(night.rate)}</b>}</div>)}</div>{showAmount&&<div className="voucher-total"><span>{l.total}</span><strong>{formatMoney(data.totalAmount)}</strong></div>}<h4>{l.policy}</h4><p className="voucher-policy">{data.reservation.cancellationPolicy||"-"}</p></div>}
    <form className="voucher-delivery" onSubmit={event=>{event.preventDefault();void queue();}}><label><span>{l.subject}</span><input required maxLength={200} value={subject} onChange={event=>setSubject(event.target.value)}/></label><label><span>{l.recipient}</span><input required type="email" maxLength={254} value={recipientEmail} onChange={event=>setRecipientEmail(event.target.value)}/></label><small>발송은 내구성 worker queue에 등록되며 같은 요청의 중복 전송은 차단됩니다.</small><div className="voucher-actions">{canExport?<><button type="button" className="secondary" disabled={!data} onClick={()=>openDocument("pdf")}>PDF 다운로드</button><button type="button" className="secondary" disabled={!data} onClick={()=>openDocument("xlsx")}>Excel</button><button type="button" className="secondary" disabled={!data} onClick={()=>openDocument("html")}>인쇄</button></>:<span className="permission-note">파일 출력 권한 없음</span>}<button className="primary" disabled={!data||!!busy}>{busy?"큐 등록 중…":l.send}</button></div></form>
  </section></div>;
}
