"use client";

/** Administrative room-type and physical-room master editor. */

import { useMemo, useState } from "react";

type RoomType={id:string;code:string;name:string;base_rate:number;capacity:number;description?:string;active?:number|boolean;version:number;physical:number};
type Room={id:string;number:string;floor:number;room_type_id:string;room_type_code:string;room_type_name:string;front_desk_status:string;housekeeping_status:string;features?:string;active?:number|boolean;version?:number};
type Editor={kind:"newType"|"editType"|"newRoom"|"bulkRooms"|"editRoom";item?:RoomType|Room}|null;
const money=(value:number)=>new Intl.NumberFormat("ko-KR",{style:"currency",currency:"KRW",maximumFractionDigits:0}).format(value);
const isActive=(value:number|boolean|undefined)=>value!==0&&value!==false;
function featureText(value?:string){try{const parsed=JSON.parse(value||"[]");return Array.isArray(parsed)?parsed.join(", "):String(value||"");}catch{return String(value||"");}}

export default function RoomMaster({types,rooms,canAdmin,busy,act}:{types:RoomType[];rooms:Room[];canAdmin:boolean;busy:string;act:(action:string,payload:Record<string,string>)=>Promise<boolean>}){
  const [tab,setTab]=useState<"types"|"rooms">("types"),[query,setQuery]=useState(""),[editor,setEditor]=useState<Editor>(null);
  const filtered=useMemo(()=>{const keyword=query.toLowerCase();return rooms.filter(room=>!keyword||`${room.number} ${room.room_type_code} ${room.room_type_name} ${room.floor}`.toLowerCase().includes(keyword));},[rooms,query]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!editor)return;const form=event.currentTarget,data=Object.fromEntries(new FormData(form).entries()) as Record<string,string>;let action="";if(editor.kind==="newType")action="create_room_type";if(editor.kind==="editType"){action="update_room_type";data.roomTypeId=(editor.item as RoomType).id;data.expectedVersion=String((editor.item as RoomType).version);data.active=data.active?"true":"false";}if(editor.kind==="newRoom")action="create_room";if(editor.kind==="bulkRooms")action="bulk_create_rooms";if(editor.kind==="editRoom"){action="update_room";data.roomId=(editor.item as Room).id;data.expectedVersion=String((editor.item as Room).version||1);data.active=data.active?"true":"false";}if(await act(action,data))setEditor(null);}
  return <section className="master-panel">
    <div className="master-head"><div><p className="eyebrow">ROOM INVENTORY MASTER</p><h2>객실 타입 · 객실 마스터</h2><p>타입과 실제 판매 객실을 제한 없이 관리하고, 한 번에 최대 500실씩 안전하게 생성합니다.</p></div><div className="master-actions">{tab==="rooms"&&<label className="master-search">⌕ <input value={query} onChange={event=>setQuery(event.target.value)} placeholder="객실번호·타입·층 검색"/></label>}{canAdmin&&tab==="types"&&<button className="primary" onClick={()=>setEditor({kind:"newType"})}>＋ 객실 타입</button>}{canAdmin&&tab==="rooms"&&<><button className="secondary" onClick={()=>setEditor({kind:"bulkRooms"})}>대량 생성</button><button className="primary" onClick={()=>setEditor({kind:"newRoom"})}>＋ 객실</button></>}</div></div>
    <div className="master-tabs"><button className={tab==="types"?"on":""} onClick={()=>setTab("types")}>객실 타입 <b>{types.length}</b></button><button className={tab==="rooms"?"on":""} onClick={()=>setTab("rooms")}>실물 객실 <b>{rooms.length}</b></button></div>
    {tab==="types"?<div className="type-master-grid">{types.map(type=><article key={type.id} className={!isActive(type.active)?"inactive":""}><div className="type-code"><span>{type.code}</span><i className={isActive(type.active)?"live":""}>{isActive(type.active)?"판매 중":"비활성"}</i></div><h3>{type.name}</h3><p>{type.description||"설명 없음"}</p><dl><div><dt>실물 객실</dt><dd>{type.physical}실</dd></div><div><dt>기준 인원</dt><dd>{type.capacity}명</dd></div><div><dt>기준 요금</dt><dd>{money(Number(type.base_rate))}</dd></div></dl>{canAdmin&&<button className="secondary wide" onClick={()=>setEditor({kind:"editType",item:type})}>타입 편집</button>}</article>)}</div>:<div className="room-master-table"><div className="room-master-row head"><span>객실</span><span>객실 타입</span><span>층</span><span>운영 상태</span><span>청소 상태</span><span>객실 특성</span><span/></div>{filtered.map(room=><div className={`room-master-row ${!isActive(room.active)?"inactive":""}`} key={room.id}><span><b>{room.number}</b><small>{isActive(room.active)?"활성":"비활성"}</small></span><span><b>{room.room_type_code}</b><small>{room.room_type_name}</small></span><span>{room.floor}F</span><span><i className={`status ${room.front_desk_status==="OCCUPIED"?"stay":"ready"}`}>{room.front_desk_status}</i></span><span><i className={`status ${room.housekeeping_status==="DIRTY"?"warn":"ready"}`}>{room.housekeeping_status}</i></span><span className="features">{featureText(room.features)||"—"}</span><span>{canAdmin&&<button className="table-edit" onClick={()=>setEditor({kind:"editRoom",item:room})}>편집</button>}</span></div>)}{filtered.length===0&&<div className="master-empty">조건에 맞는 객실이 없습니다.</div>}</div>}
    {editor&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setEditor(null)}}><form role="dialog" aria-modal="true" aria-label="객실 마스터 편집" className="modal master-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">ROOM MASTER</p><h2>{editor.kind==="newType"?"새 객실 타입":editor.kind==="editType"?"객실 타입 편집":editor.kind==="newRoom"?"새 객실":editor.kind==="bulkRooms"?"객실 대량 생성":"객실 편집"}</h2></div><button type="button" aria-label="객실 마스터 편집 닫기" onClick={()=>setEditor(null)}>×</button></div>{(editor.kind==="newType"||editor.kind==="editType")?<TypeFields item={editor.item as RoomType|undefined}/>:editor.kind==="bulkRooms"?<BulkFields types={types}/>:<RoomFields item={editor.item as Room|undefined} types={types}/>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setEditor(null)}>취소</button><button className="primary" disabled={!!busy}>{busy?"저장 중…":"저장"}</button></div></form></div>}
  </section>;
}

function TypeFields({item}:{item?:RoomType}){return <div className="master-form-grid"><label><span>타입 코드</span><input name="code" required maxLength={12} defaultValue={item?.code} placeholder="예: DLX"/></label><label className="wide"><span>타입명</span><input name="name" required maxLength={80} defaultValue={item?.name} placeholder="예: 디럭스 킹"/></label><label><span>기준 요금</span><input name="baseRate" type="number" min="0" step="100" required defaultValue={item?.base_rate}/></label><label><span>기준 인원</span><input name="capacity" type="number" min="1" max="20" required defaultValue={item?.capacity||2}/></label><label className="full"><span>설명</span><textarea name="description" maxLength={300} defaultValue={item?.description}/></label>{item&&<label className="check full"><input name="active" type="checkbox" defaultChecked={isActive(item.active)}/><span>신규 예약에 사용할 활성 타입</span></label>}</div>}
function RoomFields({item,types}:{item?:Room;types:RoomType[]}){return <div className="master-form-grid"><label><span>객실번호</span><input name="number" required maxLength={16} defaultValue={item?.number} placeholder="예: 401"/></label><label><span>층</span><input name="floor" type="number" min="-10" max="250" required defaultValue={item?.floor||1}/></label><label className="full"><span>객실 타입</span><select name="roomTypeId" required defaultValue={item?.room_type_id||types.find(type=>isActive(type.active))?.id}>{types.filter(type=>isActive(type.active)).map(type=><option key={type.id} value={type.id}>{type.code} · {type.name}</option>)}</select></label><label className="full"><span>객실 특성</span><input name="features" defaultValue={featureText(item?.features)} placeholder="쉼표로 구분: 금연, 고층, 한강 전망"/></label>{item&&<label className="check full"><input name="active" type="checkbox" defaultChecked={isActive(item.active)}/><span>판매 가능한 활성 객실</span></label>}</div>}
function BulkFields({types}:{types:RoomType[]}){return <><div className="bulk-note"><b>연속 객실번호 생성</b><span>한 번에 최대 500실까지 생성하며, 중복 번호가 하나라도 있으면 저장하지 않습니다.</span></div><div className="master-form-grid"><label><span>접두어</span><input name="prefix" maxLength={8} placeholder="선택: A"/></label><label><span>시작 번호</span><input name="startNumber" type="number" min="0" required defaultValue="401"/></label><label><span>생성 수량</span><input name="count" type="number" min="1" max="500" required defaultValue="10"/></label><label><span>번호 자릿수</span><input name="padding" type="number" min="1" max="8" required defaultValue="3"/></label><label><span>층</span><input name="floor" type="number" min="-10" max="250" required defaultValue="4"/></label><label><span>객실 타입</span><select name="roomTypeId" required>{types.filter(type=>isActive(type.active)).map(type=><option key={type.id} value={type.id}>{type.code} · {type.name}</option>)}</select></label><label className="full"><span>공통 객실 특성</span><input name="features" placeholder="금연, 고층"/></label></div></>}
