-- Generated by scripts/generate-supabase-migration.mjs. Do not edit by hand.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';
CREATE TABLE IF NOT EXISTS pms_schema_migrations (id text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());

-- Source: drizzle/0000_brief_bill_hollister.sql
CREATE TABLE "audit_logs" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"actor" text NOT NULL,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"before_json" text,
	"after_json" text,
	"created_at" text NOT NULL
);

CREATE INDEX "audit_entity_idx" ON "audit_logs" ("property_id","entity_type","entity_id","created_at");
CREATE TABLE "folio_entries" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"kind" text NOT NULL,
	"code" text NOT NULL,
	"description" text NOT NULL,
	"amount" numeric(14,2) NOT NULL,
	"payment_method" text,
	"business_date" text NOT NULL,
	"created_at" text NOT NULL,
	"created_by" text NOT NULL,
	"reverses_entry_id" text
);

CREATE INDEX "folio_reservation_idx" ON "folio_entries" ("reservation_id","created_at");
CREATE TABLE "guests" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text,
	"phone" text,
	"vip_level" text DEFAULT 'NONE' NOT NULL,
	"nationality" text,
	"preferences" text DEFAULT '[]' NOT NULL,
	"created_at" text NOT NULL
);

CREATE INDEX "guest_search_idx" ON "guests" ("property_id","last_name","first_name");
CREATE TABLE "housekeeping_tasks" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"room_id" text NOT NULL,
	"business_date" text NOT NULL,
	"status" text NOT NULL,
	"priority" integer DEFAULT 2 NOT NULL,
	"assignee" text,
	"notes" text DEFAULT '' NOT NULL,
	"updated_at" text NOT NULL
);

CREATE INDEX "hk_board_idx" ON "housekeeping_tasks" ("property_id","business_date","status");
CREATE TABLE "properties" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"code" text NOT NULL,
	"timezone" text NOT NULL,
	"currency" text NOT NULL,
	"business_date" text NOT NULL
);

CREATE TABLE "reservation_nights" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"room_id" text NOT NULL,
	"stay_date" text NOT NULL
);

CREATE UNIQUE INDEX "room_night_uq" ON "reservation_nights" ("property_id","room_id","stay_date");
CREATE TABLE "reservations" (
	"id" text PRIMARY KEY NOT NULL,
	"confirmation_no" text NOT NULL,
	"property_id" text NOT NULL,
	"guest_id" text NOT NULL,
	"room_type_id" text NOT NULL,
	"room_id" text,
	"arrival_date" text NOT NULL,
	"departure_date" text NOT NULL,
	"status" text NOT NULL,
	"adults" integer NOT NULL,
	"children" integer DEFAULT 0 NOT NULL,
	"source" text NOT NULL,
	"rate_plan" text NOT NULL,
	"nightly_rate" numeric(14,2) NOT NULL,
	"eta" text,
	"notes" text DEFAULT '' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);

CREATE UNIQUE INDEX "confirmation_uq" ON "reservations" ("property_id","confirmation_no");
CREATE INDEX "arrival_idx" ON "reservations" ("property_id","arrival_date","status");
CREATE INDEX "room_stay_idx" ON "reservations" ("room_id","arrival_date","departure_date");
CREATE TABLE "room_types" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"base_rate" numeric(14,2) NOT NULL,
	"capacity" integer NOT NULL
);

CREATE UNIQUE INDEX "room_type_code_uq" ON "room_types" ("property_id","code");
CREATE TABLE "rooms" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"room_type_id" text NOT NULL,
	"number" text NOT NULL,
	"floor" integer NOT NULL,
	"front_desk_status" text NOT NULL,
	"housekeeping_status" text NOT NULL,
	"features" text DEFAULT '[]' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL
);

CREATE UNIQUE INDEX "room_number_uq" ON "rooms" ("property_id","number");
CREATE INDEX "room_status_idx" ON "rooms" ("property_id","housekeeping_status");

-- Source: drizzle/0001_aspiring_sentry.sql
CREATE TABLE "idempotency_keys" (
	"key" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"action" text NOT NULL,
	"actor" text NOT NULL,
	"created_at" text NOT NULL
);

CREATE TABLE "outbox_events" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"topic" text NOT NULL,
	"aggregate_type" text NOT NULL,
	"aggregate_id" text NOT NULL,
	"payload_json" text NOT NULL,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"created_at" text NOT NULL,
	"published_at" text
);

CREATE INDEX "outbox_pending_idx" ON "outbox_events" ("status","created_at");

-- Source: drizzle/0002_mixed_kang.sql
CREATE TABLE "cashier_sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"actor" text NOT NULL,
	"business_date" text NOT NULL,
	"status" text NOT NULL,
	"opening_amount" numeric(14,2) NOT NULL,
	"expected_amount" numeric(14,2),
	"counted_amount" numeric(14,2),
	"variance" numeric(14,2),
	"opened_at" text NOT NULL,
	"closed_at" text
);

CREATE INDEX "cashier_open_idx" ON "cashier_sessions" ("property_id","status","actor");
CREATE UNIQUE INDEX "cashier_actor_open_uq" ON "cashier_sessions" ("property_id","actor") WHERE "status" = 'OPEN';
CREATE TABLE "night_audits" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"business_date" text NOT NULL,
	"status" text NOT NULL,
	"blockers_json" text NOT NULL,
	"summary_json" text,
	"started_at" text NOT NULL,
	"completed_at" text,
	"completed_by" text
);

CREATE UNIQUE INDEX "night_audit_property_date_uq" ON "night_audits" ("property_id","business_date");
CREATE TABLE "role_assignments" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"email" text NOT NULL,
	"role" text NOT NULL,
	"active" integer DEFAULT 1 NOT NULL,
	"created_at" text NOT NULL
);

CREATE UNIQUE INDEX "role_property_email_uq" ON "role_assignments" ("property_id","email");

-- Source: drizzle/0004_married_guardsmen.sql
CREATE TABLE "reservation_transitions" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"from_status" text NOT NULL,
	"to_status" text NOT NULL,
	"actor" text NOT NULL,
	"created_at" text NOT NULL
);

CREATE UNIQUE INDEX "reservation_transition_from_uq" ON "reservation_transitions" ("property_id","reservation_id","from_status");

-- Source: drizzle/0005_normal_frightful_four.sql
CREATE TABLE "inventory_controls" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"room_type_id" text NOT NULL,
	"stay_date" text NOT NULL,
	"sell_limit" integer,
	"closed" integer DEFAULT 0 NOT NULL,
	"min_stay" integer DEFAULT 1 NOT NULL,
	"close_to_arrival" integer DEFAULT 0 NOT NULL,
	"close_to_departure" integer DEFAULT 0 NOT NULL,
	"price_override" numeric(14,2),
	"updated_at" text NOT NULL,
	"updated_by" text NOT NULL
);

CREATE UNIQUE INDEX "inventory_control_type_date_uq" ON "inventory_controls" ("property_id","room_type_id","stay_date");
CREATE INDEX "inventory_control_calendar_idx" ON "inventory_controls" ("property_id","stay_date");
CREATE TABLE "reservation_mutations" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"expected_version" integer NOT NULL,
	"kind" text NOT NULL,
	"actor" text NOT NULL,
	"created_at" text NOT NULL
);

CREATE UNIQUE INDEX "reservation_mutation_version_uq" ON "reservation_mutations" ("property_id","reservation_id","expected_version");
CREATE TABLE "reservation_type_nights" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"room_type_id" text NOT NULL,
	"stay_date" text NOT NULL
);

CREATE UNIQUE INDEX "reservation_type_night_uq" ON "reservation_type_nights" ("reservation_id","stay_date");
CREATE INDEX "type_night_inventory_idx" ON "reservation_type_nights" ("property_id","room_type_id","stay_date");
CREATE TABLE "room_moves" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"from_room_id" text,
	"to_room_id" text NOT NULL,
	"move_date" text NOT NULL,
	"reason" text NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"actor" text NOT NULL,
	"created_at" text NOT NULL
);

CREATE INDEX "room_move_reservation_idx" ON "room_moves" ("property_id","reservation_id","created_at");

-- Source: drizzle/0006_quiet_wasp.sql
CREATE TABLE "account_profiles" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"type" text NOT NULL,
	"name" text NOT NULL,
	"external_id" text,
	"email" text,
	"phone" text,
	"negotiated_rate_code" text,
	"credit_status" text DEFAULT 'CASH' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"active" integer DEFAULT 1 NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);

CREATE UNIQUE INDEX "account_profile_external_uq" ON "account_profiles" ("property_id","type","external_id");
CREATE INDEX "account_profile_search_idx" ON "account_profiles" ("property_id","type","name");
CREATE TABLE "block_inventory" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"block_id" text NOT NULL,
	"room_type_id" text NOT NULL,
	"stay_date" text NOT NULL,
	"original_rooms" integer NOT NULL,
	"current_rooms" integer NOT NULL,
	"picked_up" integer DEFAULT 0 NOT NULL,
	"rate" numeric(14,2) NOT NULL,
	"cutoff_date" text,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" text NOT NULL
);

CREATE UNIQUE INDEX "block_inventory_type_date_uq" ON "block_inventory" ("block_id","room_type_id","stay_date");
CREATE INDEX "block_inventory_house_idx" ON "block_inventory" ("property_id","room_type_id","stay_date");
CREATE TABLE "block_pickup_nights" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"block_id" text NOT NULL,
	"rooming_entry_id" text NOT NULL,
	"room_type_id" text NOT NULL,
	"stay_date" text NOT NULL,
	"created_at" text NOT NULL
);

CREATE UNIQUE INDEX "block_pickup_entry_date_uq" ON "block_pickup_nights" ("rooming_entry_id","stay_date");
CREATE INDEX "block_pickup_block_date_idx" ON "block_pickup_nights" ("block_id","room_type_id","stay_date");
CREATE TABLE "business_blocks" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"account_profile_id" text,
	"group_profile_id" text,
	"arrival_date" text NOT NULL,
	"departure_date" text NOT NULL,
	"status" text NOT NULL,
	"reservation_method" text NOT NULL,
	"deduct_inventory" integer DEFAULT 1 NOT NULL,
	"cutoff_date" text,
	"currency" text NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"cutoff_processed_at" text,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);

CREATE UNIQUE INDEX "business_block_code_uq" ON "business_blocks" ("property_id","code");
CREATE INDEX "business_block_dates_idx" ON "business_blocks" ("property_id","arrival_date","departure_date","status");
CREATE TABLE "rooming_list_entries" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"block_id" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text,
	"phone" text,
	"arrival_date" text NOT NULL,
	"departure_date" text NOT NULL,
	"room_type_id" text NOT NULL,
	"status" text NOT NULL,
	"reservation_id" text,
	"rate" numeric(14,2) NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);

CREATE INDEX "rooming_list_block_idx" ON "rooming_list_entries" ("block_id","status","last_name");
CREATE UNIQUE INDEX "rooming_list_reservation_uq" ON "rooming_list_entries" ("reservation_id");

-- Source: drizzle/0007_overconfident_whizzer.sql
CREATE TABLE "ar_accounts" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"account_profile_id" text NOT NULL,
	"account_no" text NOT NULL,
	"name" text NOT NULL,
	"credit_limit" numeric(14,2) DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);

CREATE UNIQUE INDEX "ar_account_profile_uq" ON "ar_accounts" ("property_id","account_profile_id");
CREATE UNIQUE INDEX "ar_account_no_uq" ON "ar_accounts" ("property_id","account_no");
CREATE TABLE "ar_invoices" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"ar_account_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"folio_window_id" text NOT NULL,
	"invoice_no" text NOT NULL,
	"issued_date" text NOT NULL,
	"due_date" text NOT NULL,
	"subtotal" numeric(14,2) NOT NULL,
	"tax_amount" numeric(14,2) NOT NULL,
	"service_amount" numeric(14,2) NOT NULL,
	"total" numeric(14,2) NOT NULL,
	"status" text NOT NULL,
	"created_at" text NOT NULL,
	"created_by" text NOT NULL
);

CREATE UNIQUE INDEX "ar_invoice_no_uq" ON "ar_invoices" ("property_id","invoice_no");
CREATE INDEX "ar_invoice_account_due_idx" ON "ar_invoices" ("ar_account_id","status","due_date");
CREATE TABLE "ar_ledger_entries" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"ar_account_id" text NOT NULL,
	"invoice_id" text,
	"kind" text NOT NULL,
	"debit" numeric(14,2) DEFAULT 0 NOT NULL,
	"credit" numeric(14,2) DEFAULT 0 NOT NULL,
	"business_date" text NOT NULL,
	"payment_method" text,
	"memo" text NOT NULL,
	"created_at" text NOT NULL,
	"created_by" text NOT NULL,
	"reverses_entry_id" text
);

CREATE INDEX "ar_ledger_account_idx" ON "ar_ledger_entries" ("ar_account_id","business_date","created_at");
CREATE INDEX "ar_ledger_invoice_idx" ON "ar_ledger_entries" ("invoice_id");
CREATE TABLE "folio_entry_details" (
	"entry_id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"folio_window_id" text NOT NULL,
	"net_amount" numeric(14,2) NOT NULL,
	"tax_amount" numeric(14,2) DEFAULT 0 NOT NULL,
	"service_amount" numeric(14,2) DEFAULT 0 NOT NULL,
	"currency" text NOT NULL,
	"source_entry_id" text,
	"reason" text,
	"created_at" text NOT NULL
);

CREATE INDEX "folio_detail_window_idx" ON "folio_entry_details" ("folio_window_id","created_at");
CREATE INDEX "folio_detail_source_idx" ON "folio_entry_details" ("source_entry_id");
CREATE TABLE "folio_routing_rules" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"transaction_code" text NOT NULL,
	"target_window_id" text NOT NULL,
	"active" integer DEFAULT 1 NOT NULL,
	"created_at" text NOT NULL,
	"created_by" text NOT NULL
);

CREATE UNIQUE INDEX "folio_routing_reservation_code_uq" ON "folio_routing_rules" ("reservation_id","transaction_code");
CREATE INDEX "folio_routing_target_idx" ON "folio_routing_rules" ("target_window_id","active");
CREATE TABLE "folio_windows" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"window_no" integer NOT NULL,
	"name" text NOT NULL,
	"payee_type" text DEFAULT 'GUEST' NOT NULL,
	"payee_account_profile_id" text,
	"status" text DEFAULT 'OPEN' NOT NULL,
	"created_at" text NOT NULL,
	"created_by" text NOT NULL,
	"closed_at" text
);

CREATE UNIQUE INDEX "folio_window_reservation_no_uq" ON "folio_windows" ("reservation_id","window_no");
CREATE INDEX "folio_window_property_idx" ON "folio_windows" ("property_id","status");
CREATE TABLE "transaction_codes" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"category" text NOT NULL,
	"tax_rate" numeric(14,2) DEFAULT 0 NOT NULL,
	"service_rate" numeric(14,2) DEFAULT 0 NOT NULL,
	"active" integer DEFAULT 1 NOT NULL
);

CREATE UNIQUE INDEX "transaction_code_property_uq" ON "transaction_codes" ("property_id","code");

-- Source: drizzle/0008_graceful_bedlam.sql
CREATE TABLE "ari_updates" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"connection_id" text NOT NULL,
	"mapping_id" text NOT NULL,
	"stay_date" text NOT NULL,
	"revision" integer NOT NULL,
	"available" integer NOT NULL,
	"closed" integer DEFAULT 0 NOT NULL,
	"min_stay" integer DEFAULT 1 NOT NULL,
	"close_to_arrival" integer DEFAULT 0 NOT NULL,
	"close_to_departure" integer DEFAULT 0 NOT NULL,
	"rate" numeric(14,2) NOT NULL,
	"currency" text NOT NULL,
	"payload_json" text NOT NULL,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"created_at" text NOT NULL,
	"sent_at" text,
	"last_error" text
);

CREATE UNIQUE INDEX "ari_update_revision_uq" ON "ari_updates" ("mapping_id","stay_date","revision");
CREATE INDEX "ari_update_dispatch_idx" ON "ari_updates" ("status","created_at");
CREATE TABLE "channel_connections" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"provider" text NOT NULL,
	"external_property_id" text NOT NULL,
	"name" text NOT NULL,
	"environment" text DEFAULT 'SANDBOX' NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"last_sync_at" text,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"created_by" text NOT NULL
);

CREATE UNIQUE INDEX "channel_connection_provider_property_uq" ON "channel_connections" ("property_id","provider","external_property_id");
CREATE INDEX "channel_connection_status_idx" ON "channel_connections" ("property_id","status");
CREATE TABLE "channel_mappings" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"connection_id" text NOT NULL,
	"room_type_id" text NOT NULL,
	"external_room_type_id" text NOT NULL,
	"rate_plan" text NOT NULL,
	"external_rate_plan_id" text NOT NULL,
	"active" integer DEFAULT 1 NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);

CREATE UNIQUE INDEX "channel_mapping_external_uq" ON "channel_mappings" ("connection_id","external_room_type_id","external_rate_plan_id");
CREATE INDEX "channel_mapping_internal_idx" ON "channel_mappings" ("property_id","room_type_id","rate_plan");
CREATE TABLE "channel_reservation_links" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"connection_id" text NOT NULL,
	"external_reservation_id" text NOT NULL,
	"reservation_id" text NOT NULL,
	"last_revision" integer NOT NULL,
	"status" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);

CREATE UNIQUE INDEX "channel_reservation_external_uq" ON "channel_reservation_links" ("connection_id","external_reservation_id");
CREATE UNIQUE INDEX "channel_reservation_internal_uq" ON "channel_reservation_links" ("connection_id","reservation_id");
CREATE TABLE "inbound_channel_messages" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"connection_id" text NOT NULL,
	"provider" text NOT NULL,
	"message_id" text NOT NULL,
	"event_type" text NOT NULL,
	"external_reservation_id" text NOT NULL,
	"revision" integer NOT NULL,
	"payload_json" text NOT NULL,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"reservation_id" text,
	"last_error" text,
	"received_at" text NOT NULL,
	"processed_at" text
);

CREATE UNIQUE INDEX "inbound_channel_message_uq" ON "inbound_channel_messages" ("connection_id","message_id");
CREATE INDEX "inbound_channel_dlq_idx" ON "inbound_channel_messages" ("status","received_at");
CREATE TABLE "integration_delivery_attempts" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"direction" text NOT NULL,
	"provider" text NOT NULL,
	"aggregate_type" text NOT NULL,
	"aggregate_id" text NOT NULL,
	"attempt_no" integer NOT NULL,
	"status" text NOT NULL,
	"http_status" integer,
	"error_code" text,
	"error_message" text,
	"payload_json" text NOT NULL,
	"created_at" text NOT NULL,
	"created_by" text NOT NULL
);

CREATE INDEX "integration_attempt_aggregate_idx" ON "integration_delivery_attempts" ("aggregate_type","aggregate_id","attempt_no");
CREATE INDEX "integration_attempt_failure_idx" ON "integration_delivery_attempts" ("status","created_at");

-- Source: drizzle/0009_clear_living_mummy.sql
CREATE TABLE "report_exports" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"report_key" text NOT NULL,
	"format" text NOT NULL,
	"filters_json" text NOT NULL,
	"row_count" integer NOT NULL,
	"status" text NOT NULL,
	"requested_by" text NOT NULL,
	"created_at" text NOT NULL,
	"completed_at" text
);

CREATE INDEX "report_export_actor_idx" ON "report_exports" ("property_id","requested_by","created_at");
CREATE INDEX "report_export_status_idx" ON "report_exports" ("property_id","status","created_at");
ALTER TABLE "room_types" ADD "description" text DEFAULT '' NOT NULL;
ALTER TABLE "room_types" ADD "active" integer DEFAULT 1 NOT NULL;
ALTER TABLE "rooms" ADD "active" integer DEFAULT 1 NOT NULL;

-- Source: drizzle/0010_simple_killmonger.sql
ALTER TABLE "room_types" ADD "version" integer DEFAULT 1 NOT NULL;


-- Reporting and operational access paths.
CREATE INDEX report_reservation_filter_idx ON reservations(property_id,status,source,room_type_id,arrival_date,departure_date);
CREATE INDEX report_folio_business_idx ON folio_entries(property_id,business_date,kind,payment_method);
CREATE INDEX report_audit_created_idx ON audit_logs(property_id,created_at,action,actor);

-- Serialize inventory decisions per property/type/date to prevent concurrent oversell.
CREATE OR REPLACE FUNCTION pms_lock_inventory(p_property text, p_room_type text, p_stay_date text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(p_property || ':' || p_room_type || ':' || p_stay_date, 0));
END;
$$;

CREATE OR REPLACE FUNCTION pms_reservation_capacity_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  capacity_limit integer;
  sold integer;
  held integer;
  is_closed integer;
BEGIN
  PERFORM pms_lock_inventory(NEW.property_id, NEW.room_type_id, NEW.stay_date);
  SELECT COALESCE(ic.closed,0), COALESCE(ic.sell_limit,
    (SELECT COUNT(*) FROM rooms r WHERE r.property_id=NEW.property_id AND r.room_type_id=NEW.room_type_id AND r.active=1 AND r.housekeeping_status<>'OUT_OF_SERVICE'))
  INTO is_closed, capacity_limit
  FROM (SELECT 1) seed LEFT JOIN inventory_controls ic
    ON ic.property_id=NEW.property_id AND ic.room_type_id=NEW.room_type_id AND ic.stay_date=NEW.stay_date;
  IF is_closed=1 THEN RAISE EXCEPTION 'room type closed'; END IF;
  SELECT COUNT(*) INTO sold FROM reservation_type_nights
    WHERE property_id=NEW.property_id AND room_type_id=NEW.room_type_id AND stay_date=NEW.stay_date;
  SELECT COALESCE(SUM(bi.current_rooms-bi.picked_up),0) INTO held
    FROM block_inventory bi JOIN business_blocks bb ON bb.id=bi.block_id
    WHERE bi.property_id=NEW.property_id AND bi.room_type_id=NEW.room_type_id AND bi.stay_date=NEW.stay_date
      AND bb.deduct_inventory=1 AND bb.status IN ('TENTATIVE','DEFINITE');
  IF sold+held>=capacity_limit THEN RAISE EXCEPTION 'room type sold out'; END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER reservation_type_nights_capacity BEFORE INSERT ON reservation_type_nights
FOR EACH ROW EXECUTE FUNCTION pms_reservation_capacity_guard();

CREATE OR REPLACE FUNCTION pms_block_inventory_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  capacity_limit integer;
  sold integer;
  held integer;
  deducts integer;
BEGIN
  IF NEW.original_rooms<0 OR NEW.current_rooms<0 OR NEW.picked_up<0 OR NEW.current_rooms<NEW.picked_up OR NEW.rate<0 THEN
    RAISE EXCEPTION 'invalid block inventory';
  END IF;
  SELECT deduct_inventory INTO deducts FROM business_blocks WHERE id=NEW.block_id;
  IF COALESCE(deducts,0)=1 THEN
    PERFORM pms_lock_inventory(NEW.property_id, NEW.room_type_id, NEW.stay_date);
    SELECT COALESCE(ic.sell_limit,
      (SELECT COUNT(*) FROM rooms r WHERE r.property_id=NEW.property_id AND r.room_type_id=NEW.room_type_id AND r.active=1 AND r.housekeeping_status<>'OUT_OF_SERVICE'))
    INTO capacity_limit
    FROM (SELECT 1) seed LEFT JOIN inventory_controls ic
      ON ic.property_id=NEW.property_id AND ic.room_type_id=NEW.room_type_id AND ic.stay_date=NEW.stay_date;
    SELECT COUNT(*) INTO sold FROM reservation_type_nights
      WHERE property_id=NEW.property_id AND room_type_id=NEW.room_type_id AND stay_date=NEW.stay_date;
    SELECT COALESCE(SUM(bi.current_rooms-bi.picked_up),0) INTO held
      FROM block_inventory bi JOIN business_blocks bb ON bb.id=bi.block_id
      WHERE bi.property_id=NEW.property_id AND bi.room_type_id=NEW.room_type_id AND bi.stay_date=NEW.stay_date
        AND (TG_OP='INSERT' OR bi.id<>OLD.id) AND bb.deduct_inventory=1 AND bb.status IN ('TENTATIVE','DEFINITE');
    IF sold+held+(NEW.current_rooms-NEW.picked_up)>capacity_limit THEN RAISE EXCEPTION 'block inventory sold out'; END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER block_inventory_capacity_insert BEFORE INSERT ON block_inventory
FOR EACH ROW EXECUTE FUNCTION pms_block_inventory_guard();
CREATE TRIGGER block_inventory_capacity_update BEFORE UPDATE ON block_inventory
FOR EACH ROW EXECUTE FUNCTION pms_block_inventory_guard();

CREATE OR REPLACE FUNCTION pms_block_pickup_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pms_lock_inventory(NEW.property_id, NEW.room_type_id, NEW.stay_date);
  IF NOT EXISTS (SELECT 1 FROM block_inventory WHERE block_id=NEW.block_id AND room_type_id=NEW.room_type_id AND stay_date=NEW.stay_date AND picked_up<current_rooms) THEN
    RAISE EXCEPTION 'block allocation exhausted';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION pms_block_pickup_apply()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP='INSERT' THEN
    UPDATE block_inventory SET picked_up=picked_up+1,version=version+1,updated_at=NEW.created_at
      WHERE block_id=NEW.block_id AND room_type_id=NEW.room_type_id AND stay_date=NEW.stay_date;
    RETURN NEW;
  END IF;
  UPDATE block_inventory SET picked_up=GREATEST(0,picked_up-1),version=version+1,updated_at=clock_timestamp()::text
    WHERE block_id=OLD.block_id AND room_type_id=OLD.room_type_id AND stay_date=OLD.stay_date;
  RETURN OLD;
END;
$$;

CREATE TRIGGER block_pickup_validate BEFORE INSERT ON block_pickup_nights FOR EACH ROW EXECUTE FUNCTION pms_block_pickup_guard();
CREATE TRIGGER block_pickup_increment AFTER INSERT ON block_pickup_nights FOR EACH ROW EXECUTE FUNCTION pms_block_pickup_apply();
CREATE TRIGGER block_pickup_decrement AFTER DELETE ON block_pickup_nights FOR EACH ROW EXECUTE FUNCTION pms_block_pickup_apply();

CREATE OR REPLACE FUNCTION pms_inventory_control_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.sell_limit<0 OR NEW.min_stay<1 OR NEW.price_override<0 THEN RAISE EXCEPTION 'invalid inventory control'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER inventory_controls_validate_insert BEFORE INSERT ON inventory_controls FOR EACH ROW EXECUTE FUNCTION pms_inventory_control_guard();
CREATE TRIGGER inventory_controls_validate_update BEFORE UPDATE ON inventory_controls FOR EACH ROW EXECUTE FUNCTION pms_inventory_control_guard();

CREATE OR REPLACE FUNCTION pms_folio_entry_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.amount<=0 OR NEW.kind NOT IN ('CHARGE','PAYMENT','CHARGE_REVERSAL','PAYMENT_REVERSAL','REFUND') THEN RAISE EXCEPTION 'invalid folio entry'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER folio_entries_validate_insert BEFORE INSERT ON folio_entries FOR EACH ROW EXECUTE FUNCTION pms_folio_entry_guard();

CREATE OR REPLACE FUNCTION pms_folio_detail_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE entry_amount numeric(14,2);
BEGIN
  SELECT amount INTO entry_amount FROM folio_entries WHERE id=NEW.entry_id;
  IF NEW.net_amount<0 OR NEW.tax_amount<0 OR NEW.service_amount<0 OR ABS((NEW.net_amount+NEW.tax_amount+NEW.service_amount)-entry_amount)>0.011
    OR NOT EXISTS (SELECT 1 FROM folio_windows WHERE id=NEW.folio_window_id AND reservation_id=NEW.reservation_id AND status='OPEN')
  THEN RAISE EXCEPTION 'invalid folio detail'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER folio_details_validate_insert BEFORE INSERT ON folio_entry_details FOR EACH ROW EXECUTE FUNCTION pms_folio_detail_guard();

CREATE OR REPLACE FUNCTION pms_ar_ledger_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.debit<0 OR NEW.credit<0 OR (NEW.debit=0 AND NEW.credit=0) OR (NEW.debit>0 AND NEW.credit>0)
    OR NEW.kind NOT IN ('INVOICE','PAYMENT','CREDIT','ADJUSTMENT','REVERSAL') THEN RAISE EXCEPTION 'invalid ar ledger entry'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER ar_ledger_validate_insert BEFORE INSERT ON ar_ledger_entries FOR EACH ROW EXECUTE FUNCTION pms_ar_ledger_guard();

CREATE OR REPLACE FUNCTION pms_integration_attempt_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.attempt_no<1 OR NEW.direction NOT IN ('INBOUND','OUTBOUND') OR NEW.status NOT IN ('ACKED','FAILED') THEN RAISE EXCEPTION 'invalid integration attempt'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER integration_attempts_validate_insert BEFORE INSERT ON integration_delivery_attempts FOR EACH ROW EXECUTE FUNCTION pms_integration_attempt_guard();

CREATE OR REPLACE FUNCTION pms_immutable_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '%', TG_ARGV[0];
END;
$$;
CREATE TRIGGER folio_entries_no_update BEFORE UPDATE ON folio_entries FOR EACH ROW EXECUTE FUNCTION pms_immutable_guard('folio entries are immutable');
CREATE TRIGGER folio_entries_no_delete BEFORE DELETE ON folio_entries FOR EACH ROW EXECUTE FUNCTION pms_immutable_guard('folio entries are immutable');
CREATE TRIGGER folio_details_no_update BEFORE UPDATE ON folio_entry_details FOR EACH ROW EXECUTE FUNCTION pms_immutable_guard('folio details are immutable');
CREATE TRIGGER folio_details_no_delete BEFORE DELETE ON folio_entry_details FOR EACH ROW EXECUTE FUNCTION pms_immutable_guard('folio details are immutable');
CREATE TRIGGER ar_ledger_no_update BEFORE UPDATE ON ar_ledger_entries FOR EACH ROW EXECUTE FUNCTION pms_immutable_guard('ar ledger entries are immutable');
CREATE TRIGGER ar_ledger_no_delete BEFORE DELETE ON ar_ledger_entries FOR EACH ROW EXECUTE FUNCTION pms_immutable_guard('ar ledger entries are immutable');
CREATE TRIGGER integration_attempts_no_update BEFORE UPDATE ON integration_delivery_attempts FOR EACH ROW EXECUTE FUNCTION pms_immutable_guard('integration attempts are immutable');
CREATE TRIGGER integration_attempts_no_delete BEFORE DELETE ON integration_delivery_attempts FOR EACH ROW EXECUTE FUNCTION pms_immutable_guard('integration attempts are immutable');


-- The browser-facing Supabase roles have no direct PMS table access; all access is server mediated.
ALTER TABLE public."audit_logs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."audit_logs" FROM anon, authenticated;
ALTER TABLE public."folio_entries" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."folio_entries" FROM anon, authenticated;
ALTER TABLE public."guests" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."guests" FROM anon, authenticated;
ALTER TABLE public."housekeeping_tasks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."housekeeping_tasks" FROM anon, authenticated;
ALTER TABLE public."properties" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."properties" FROM anon, authenticated;
ALTER TABLE public."reservation_nights" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."reservation_nights" FROM anon, authenticated;
ALTER TABLE public."reservations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."reservations" FROM anon, authenticated;
ALTER TABLE public."room_types" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."room_types" FROM anon, authenticated;
ALTER TABLE public."rooms" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."rooms" FROM anon, authenticated;
ALTER TABLE public."idempotency_keys" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."idempotency_keys" FROM anon, authenticated;
ALTER TABLE public."outbox_events" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."outbox_events" FROM anon, authenticated;
ALTER TABLE public."cashier_sessions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."cashier_sessions" FROM anon, authenticated;
ALTER TABLE public."night_audits" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."night_audits" FROM anon, authenticated;
ALTER TABLE public."role_assignments" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."role_assignments" FROM anon, authenticated;
ALTER TABLE public."reservation_transitions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."reservation_transitions" FROM anon, authenticated;
ALTER TABLE public."inventory_controls" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."inventory_controls" FROM anon, authenticated;
ALTER TABLE public."reservation_mutations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."reservation_mutations" FROM anon, authenticated;
ALTER TABLE public."reservation_type_nights" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."reservation_type_nights" FROM anon, authenticated;
ALTER TABLE public."room_moves" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."room_moves" FROM anon, authenticated;
ALTER TABLE public."account_profiles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."account_profiles" FROM anon, authenticated;
ALTER TABLE public."block_inventory" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."block_inventory" FROM anon, authenticated;
ALTER TABLE public."block_pickup_nights" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."block_pickup_nights" FROM anon, authenticated;
ALTER TABLE public."business_blocks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."business_blocks" FROM anon, authenticated;
ALTER TABLE public."rooming_list_entries" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."rooming_list_entries" FROM anon, authenticated;
ALTER TABLE public."ar_accounts" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."ar_accounts" FROM anon, authenticated;
ALTER TABLE public."ar_invoices" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."ar_invoices" FROM anon, authenticated;
ALTER TABLE public."ar_ledger_entries" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."ar_ledger_entries" FROM anon, authenticated;
ALTER TABLE public."folio_entry_details" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."folio_entry_details" FROM anon, authenticated;
ALTER TABLE public."folio_routing_rules" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."folio_routing_rules" FROM anon, authenticated;
ALTER TABLE public."folio_windows" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."folio_windows" FROM anon, authenticated;
ALTER TABLE public."transaction_codes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."transaction_codes" FROM anon, authenticated;
ALTER TABLE public."ari_updates" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."ari_updates" FROM anon, authenticated;
ALTER TABLE public."channel_connections" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."channel_connections" FROM anon, authenticated;
ALTER TABLE public."channel_mappings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."channel_mappings" FROM anon, authenticated;
ALTER TABLE public."channel_reservation_links" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."channel_reservation_links" FROM anon, authenticated;
ALTER TABLE public."inbound_channel_messages" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."inbound_channel_messages" FROM anon, authenticated;
ALTER TABLE public."integration_delivery_attempts" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."integration_delivery_attempts" FROM anon, authenticated;
ALTER TABLE public."report_exports" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."report_exports" FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
INSERT INTO pms_schema_migrations(id) VALUES ('202607160001_aurora_pms') ON CONFLICT (id) DO NOTHING;
COMMIT;
